namespace MX.NetworkProtocol
{
    public enum WebAPIErrorCode
    {
        None,
        InvalidPacket,
        InvalidProtocol,
        InvalidSession,
        InvalidVersion,
        InternalServerError,
        DBError,
        InvalidToken,
        FailedToLockAccount,
        InvalidCheatError,
        AccountCurrencyCannotAffordCost,
        ExceedTranscendenceCountLimit,
        MailBoxFull,
        InventoryAlreadyFull,
        AccountNotFound,
        DataClassNotFound,
        DataEntityNotFound,
        AccountGemPaidCannotAffordCost,
        AccountGemBonusCannotAffordCost,
        AccountItemCannotAffordCost,
        APITimeoutError,
        FunctionTimeoutError,
        DBDistributeTransactionError,
        OccasionalJobError,
        FailedToConsumeParcel = 0x64,
        InvalidString = 0xC8,
        InvalidStringLength,
        EmptyString,
        SpecialSymbolNotAllowed,
        InvalidDate = 0x12C,
        CoolTimeRemain,
        TimeElapseError,
        ClientSendBadRequest = 0x190,
        ClientSendTooManyRequest,
        ClientSuspectedAsCheater,
        ServerFailedToHandleRequest = 0x1F4,
        DocumentDBFailedToHandleRequest,
        ServerCacheFailedToHandleRequest,
        ReconnectBundleUpdateRequired = 0x320,
        GatewayMakeStandbyNotSupport = 0x384,
        GatewayPassCheckNotSupport,
        GatewayWaitingTicketTimeOut,
        ClientUpdateRequire,
        AccountCreateNoDevId = 0x3E8,
        AccountCreateDuplicatedDevId,
        AccountAuthEmptyDevId,
        AccountAuthNotCreated,
        AccountAccessControlWithoutPermission,
        AccountNicknameEmptyString,
        AccountNicknameSameName,
        AccountNicknameWithInvalidString,
        AccountNicknameWithInvalidLength,
        YostarServerNotSuccessStatusCode,
        YostarNetworkException,
        YostarException,
        AccoountPassCheckNotSupportCheat,
        AccountCreateFail,
        AccountAddPubliserAccountFail,
        AccountAddDevIdFail,
        AccountCreateAlreadyPublisherAccoundId,
        AccountUpdateStateFail,
        YostarCheckFail,
        EnterTicketInvalid,
        EnterTicketTimeOut,
        EnterTicketUsed,
        AccountCommentLengthOverLimit,
        AccountUpdateBirthdayFailed,
        AccountLoginError,
        AccountCurrencySyncError,
        InvalidClientCookie,
        CharacterNotFound = 0x7D0,
        CharacterLocked,
        CharacterAlreadyHas,
        CharacterAssignedEchelon,
        CharacterFavorDownException,
        CharacterFavorMaxLevelExceed,
        CannotLevelUpSkill,
        CharacterLevelAlreadyMax,
        InvalidCharacterExpGrowthRequest,
        CharacterWeaponDataNotFound,
        CharacterWeaponNotFound,
        CharacterWeaponAlreadyUnlocked,
        CharacterWeaponUnlockConditionFail,
        CharacterWeaponExpGrowthNotValidItem,
        InvalidCharacterWeaponExpGrowthRequest,
        CharacterWeaponTranscendenceRecipeNotFound,
        CharacterWeaponTranscendenceConditionFail,
        CharacterWeaponUpdateFail,
        CharacterGearNotFound,
        CharacterGearAlreadyEquiped,
        CharacterGearCannotTierUp,
        CharacterGearCannotUnlock,
        CharacterCostumeNotFound,
        CharacterCostumeAlreadySet,
        CharacterCannotEquipCostume,
        InvalidCharacterSkillLevelUpdateRequest,
        InvalidCharacterPotentialGrowthRequest,
        CharacterPotentialGrowthDataNotFound,
        EquipmentNotFound = 0xBB8,
        InvalidEquipmentExpGrowthRequest,
        EquipmentNotMatchingSlotItemCategory,
        EquipmentLocked,
        EquipmentAlreadyEquiped,
        EquipmentConsumeItemLimitCountOver,
        EquipmentNotEquiped,
        EquipmentCanNotEquip,
        EquipmentIngredientEmtpy,
        EquipmentCannotLevelUp,
        EquipmentCannotTierUp,
        EquipmentGearCannotUnlock,
        EquipmentBatchGrowthNotValid,
        ItemNotFound = 0xFA0,
        ItemLocked,
        ItemCreateWithoutStackCount,
        ItemCreateStackCountFull,
        ItemNotUsingType,
        ItemEnchantIngredientFail,
        ItemInvalidConsumeRequest,
        ItemInsufficientStackCount,
        ItemOverExpirationDateTime,
        ItemCannotAutoSynth,
        EchelonEmptyLeader = 0x1388,
        EchelonNotFound,
        EchelonNotDeployed,
        EchelonSlotOverMaxCount,
        EchelonAssignCharacterOnOtherEchelon,
        EchelonTypeNotAcceptable,
        EchelonEmptyNotAcceptable,
        EchelonPresetInvalidSave,
        EchelonPresetLabelLengthInvalid,
        CampaignStageNotOpen = 0x1770,
        CampaignStagePlayLimit,
        CampaignStageEnterFail,
        CampaignStageInvalidSaveData,
        CampaignStageNotPlayerTurn,
        CampaignStageStageNotFound,
        CampaignStageHistoryNotFound,
        CampaignStageChapterNotFound,
        CampaignStageEchelonNotFound,
        CampaignStageWithdrawedCannotReUse,
        CampaignStageChapterRewardInvalidReward,
        CampaignStageChapterRewardAlreadyReceived,
        CampaignStageTacticWinnerInvalid,
        CampaignStageActionCountZero,
        CampaignStageHealNotAcceptable,
        CampaignStageHealLimit,
        CampaignStageLocationCanNotEngage,
        CampaignEncounterWaitingCannotEndTurn,
        CampaignTacticResultEmpty,
        CampaignPortalExitNotFound,
        CampaignCannotReachDestination,
        CampaignChapterRewardConditionNotSatisfied,
        CampaignStageDataInvalid,
        ContentSweepNotOpened,
        CampaignTacticSkipFailed,
        CampaignUnableToRemoveFixedEchelon,
        CampaignCharacterIsNotWhitelist,
        CampaignFailedToSkipStrategy,
        InvalidSweepRequest,
        MailReceiveRequestInvalid = 0x1B58,
        MissionCannotComplete = 0x1F40,
        MissionRewardInvalid,
        AttendanceInvalid = 0x2328,
        ShopExcelNotFound = 0x2710,
        ShopAndGoodsNotMatched,
        ShopGoodsNotFound,
        ShopExceedPurchaseCountLimit,
        ShopCannotRefresh,
        ShopInfoNotFound,
        ShopCannotPurchaseActionPointLimitOver,
        ShopNotOpened,
        ShopInvalidGoods,
        ShopInvalidCostOrReward,
        ShopEligmaOverPurchase,
        ShopFreeRecruitInvalid,
        ShopNewbieGachaInvalid,
        ShopCannotNewGoodsRefresh,
        GachaCostNotValid,
        ShopRestrictBuyWhenInventoryFull,
        BeforehandGachaMetadataNotFound,
        BeforehandGachaCandidateNotFound,
        BeforehandGachaInvalidLastIndex,
        BeforehandGachaInvalidSaveIndex,
        BeforehandGachaInvalidPickIndex,
        BeforehandGachaDuplicatedResults,
        RecipeCraftNoData = 0x2AF8,
        RecipeCraftInsufficientIngredients,
        RecipeCraftDataError,
        MemoryLobbyNotFound = 0x2EE0,
        LobbyModeChangeFailed,
        CumulativeTimeRewardNotFound = 0x32C8,
        CumulativeTimeRewardAlreadyReceipt,
        CumulativeTimeRewardInsufficientConnectionTime,
        OpenConditionClosed = 0x36B0,
        OpenConditionSetNotSupport,
        CafeNotFound = 0x3A98,
        CafeFurnitureNotFound,
        CafeDeployFail,
        CafeRelocateFail,
        CafeInteractionNotFound,
        CafeProductionEmpty,
        CafeRankUpFail,
        CafePresetNotFound,
        CafeRenamePresetFail,
        CafeClearPresetFail,
        CafeUpdatePresetFurnitureFail,
        CafeReservePresetActivationTimeFail,
        CafePresetApplyFail,
        CafePresetIsEmpty,
        CafeAlreadyVisitCharacter,
        CafeCannotSummonCharacter,
        CafeCanRefreshVisitCharacter,
        CafeAlreadyInteraction,
        CafeTemplateNotFound,
        CafeAlreadyOpened,
        ScenarioMode_Fail = 0x3E80,
        ScenarioMode_DuplicatedScenarioModeId,
        ScenarioMode_LimitClearedScenario,
        ScenarioMode_LimitAccountLevel,
        ScenarioMode_LimitClearedStage,
        ScenarioMode_LimitClubStudent,
        ScenarioMode_FailInDBProcess,
        ScenarioGroup_DuplicatedScenarioGroupId,
        ScenarioGroup_FailInDBProcess,
        ScenarioGroup_DataNotFound,
        ScenarioGroup_MeetupConditionFail,
        CraftInfoNotFound = 0x4268,
        CraftCanNotCreateNode,
        CraftCanNotUpdateNode,
        CraftCanNotBeginProcess,
        CraftNodeDepthError,
        CraftAlreadyProcessing,
        CraftCanNotCompleteProcess,
        CraftProcessNotComplete,
        CraftInvalidIngredient,
        CraftError,
        CraftInvalidData,
        CraftNotAvailableToCafePresets,
        CraftNotEnoughEmptySlotCount,
        CraftInvalidPresetSlotDB,
        RaidExcelDataNotFound = 0x4650,
        RaidSeasonNotOpen,
        RaidDBDataNotFound,
        RaidBattleNotFound,
        RaidBattleUpdateFail,
        RaidCompleteListEmpty,
        RaidRoomCanNotCreate,
        RaidActionPointZero,
        RaidTicketZero,
        RaidRoomCanNotJoin,
        RaidRoomMaxPlayer,
        RaidRewardDataNotFound,
        RaidSeasonRewardNotFound,
        RaidSeasonAlreadyReceiveReward,
        RaidSeasonAddRewardPointError,
        RaidSeasonRewardNotUpdate,
        RaidSeasonReceiveRewardFail,
        RaidSearchNotFound,
        RaidShareNotFound,
        RaidEndRewardFlagError,
        RaidCanNotFoundPlayer,
        RaidAlreadyParticipateCharacters,
        RaidClearHistoryNotSave,
        RaidBattleAlreadyEnd,
        RaidEchelonNotFound,
        RaidSeasonOpen,
        RaidRoomIsAlreadyClose,
        RaidRankingNotFound,
        WeekDungeonInfoNotFound = 0x4A38,
        WeekDungeonNotOpenToday,
        WeekDungeonBattleWinnerInvalid,
        WeekDungeonInvalidSaveData,
        FindGiftRewardNotFound = 0x4E20,
        FindGiftRewardAlreadyAcquired,
        FindGiftClearCountOverTotalCount,
        ArenaInfoNotFound = 0x5208,
        ArenaGroupNotFound,
        ArenaRankHistoryNotFound,
        ArenaRankInvalid,
        ArenaBattleFail,
        ArenaDailyRewardAlreadyBeenReceived,
        ArenaNoSeasonAvailable,
        ArenaAttackCoolTime,
        ArenaOpponentAlreadyBeenAttacked,
        ArenaOpponentRankInvalid,
        ArenaNeedFormationSetting,
        ArenaNoHistory,
        ArenaInvalidRequest,
        ArenaInvalidIndex,
        ArenaNotFoundBattle,
        ArenaBattleTimeOver,
        ArenaRefreshTimeOver,
        ArenaEchelonSettingTimeOver,
        ArenaCannotReceiveReward,
        ArenaRewardNotExist,
        ArenaCannotSetMap,
        ArenaDefenderRankChange,
        AcademyNotFound = 0x55F0,
        AcademyScheduleTableNotFound,
        AcademyScheduleOperationNotFound,
        AcademyAlreadyAttendedSchedule,
        AcademyAlreadyAttendedFavorSchedule,
        AcademyRewardCharacterNotFound,
        AcademyScheduleCanNotAttend,
        AcademyTicketZero,
        AcademyMessageCanNotSend,
        ContentSaveDBNotFound = 0x6590,
        ContentSaveDBEntranceFeeEmpty,
        AccountBanned = 0x6978,
        ServerNowLoadingProhibitedWord = 0x6D60,
        ServerIsUnderMaintenance,
        ServerMaintenanceSoon,
        AccountIsNotInWhiteList,
        ServerContentsLockUpdating,
        ServerContentsLock,
        CouponIsEmpty = 0x7148,
        CouponIsInvalid,
        UseCouponUsedListReadFail,
        UseCouponUsedCoupon,
        UseCouponNotFoundSerials,
        UseCouponDeleteSerials,
        UseCouponUnapprovedSerials,
        UseCouponExpiredSerials,
        UseCouponMaximumSerials,
        UseCouponNotFoundMeta,
        UseCouponDuplicateUseCoupon,
        UseCouponDuplicateUseSerial,
        BillingStartShopCashIdNotFound = 0x7530,
        BillingStartNotServiceTime,
        BillingStartUseConditionCheckError,
        BillingStartSmallLevel,
        BillingStartMaxPurchaseCount,
        BillingStartFailAddOrder,
        BillingStartExistPurchase,
        BillingEndFailGetOrder,
        BillingEndShopCashIdNotFound,
        BillingEndProductIdNotFound,
        BillingEndMonthlyProductIdNotFound,
        BillingEndInvalidState,
        BillingEndFailUpdteState,
        BillingEndFailSendMail,
        BillingEndInvalidAccount,
        BillingEndNotFoundPurchaseCount,
        BillingEndFailUpdteMonthlyProduct,
        BillingStartMailFull,
        BillingStartInventoryAndMailFull,
        BillingEndRecvedErrorMonthlyProduct,
        MonthlyProductNotOutdated,
        ClanNotFound = 0x7918,
        ClanSearchFailed,
        ClanEmptySearchString,
        ClanAccountAlreadyJoinedClan,
        ClanAccountAlreadyQuitClan,
        ClanCreateFailed,
        ClanMemberExceedCapacity,
        ClanDoesNotHavePermission,
        ClanTargetAccountIsNotApplicant,
        ClanMemberNotFound,
        ClanCanNotKick,
        ClanCanNotDismiss,
        ClanCanNotQuit,
        ClanRejoinCoolOff,
        ClanChangeMemberGradeFailed,
        ClanHasBeenDisMissed,
        ClanCannotChangeJoinOption,
        ClanExceedConferCountLimit,
        ClanBusy,
        ClanNameEmptyString,
        ClanNameWithInvalidLength,
        ClanAssistCharacterAlreadyDeployed,
        ClanAssistNotValidUse,
        ClanAssistCharacterChanged,
        ClanAssistCoolTime,
        ClanAssistAlreadyUsedInRaidRoom,
        ClanAssistAlreadyUsedInTimeAttackDungeonRoom,
        ClanAssistEchelonHasAssistOnly,
        PaymentInvalidSign = 0x7D00,
        PaymentInvalidSeed1,
        PaymentInvalidSeed2,
        PaymentInvalidInput,
        PaymentNotFoundPurchase,
        PaymentGetPurchaseOrderNotZero,
        PaymentSetPurchaseOrderNotZero,
        PaymentException,
        PaymentInvalidState,
        SessionNotFound = 0x80E8,
        SessionParseFail,
        SessionInvalidInput,
        SessionNotAuth,
        SessionDuplicateLogin,
        SessionTimeOver,
        SessionInvalidVersion,
        SessionChangeDate,
        CallName_RenameCoolTime = 0x84D0,
        CallName_EmptyString,
        CallName_InvalidString,
        CallName_TTSServerIsNotAvailable,
        CouchbaseInvalidCas = 0x88B8,
        CouchbaseOperationFailed,
        CouchbaseRollBackFailed,
        EventContentCannotSelectBuff = 0x8CA0,
        EventContentNoBuffGroupAvailable,
        EventContentBuffGroupIdDuplicated,
        EventContentNotOpen,
        EventContentNoTotalRewardAvailable,
        EventContentBoxGachaPurchaseFailed,
        EventContentBoxGachaCannotRefresh,
        EventContentCardShopCannotShuffle,
        EventContentElementDoesNotExist,
        EventContentElementAlreadyPurchased,
        EventContentLocationNotFound,
        EventContentLocationScheduleCanNotAttend,
        EventContentDiceRaceDataNotFound,
        EventContentDiceRaceAlreadyReceiveLapRewardAll,
        EventContentDiceRaceInvalidDiceRaceResultType,
        EventContentTreasureDataNotFound,
        EventContentTreasureNotComplete,
        EventContentTreasureFlipFailed,
        MiniGameStageIsNotOpen = 0x9088,
        MiniGameStageInvalidResult,
        MiniGameShootingStageInvlid,
        MiniGameShootingCannotSweep,
        MiniGameTableBoardSaveNotExist,
        MiniGameTableBoardPlayerCannotMove,
        MiniGameTableBoardNoActiveEncounter,
        MiniGameTableBoardInvalidEncounterRequest,
        MiniGameTableBoardProcessEncounterFailed,
        MiniGameTableBoardItemNotExist,
        MiniGameTableBoardInvalidItemUse,
        MiniGameTableBoardInvalidClearThemaRequest,
        MiniGameTableBoardInvalidSeason,
        MiniGameTableBoardInvalidResurrectRequest,
        MiniGameTableBoardSweepConditionFail,
        MiniGameTableBoardInvalidData,
        MiniGameDreamCannotStartNewGame,
        MiniGameDreamCannotApplyMultiplier,
        MiniGameDreamCannotReset,
        MiniGameDreamNotEnoughActionCount,
        MiniGameDreamSaveNotExist,
        MiniGameDreamActionCountRemain,
        MiniGameDreamRoundNotComplete,
        MiniGameDreamRewardAlreadyReceived,
        MiniGameDreamRoundCompleted,
        MiniGameShouldReceiveEndingReward,
        ProofTokenNotSubmitted = 0x9470,
        SchoolDungeonInfoNotFound = 0x9858,
        SchoolDungeonNotOpened,
        SchoolDungeonInvalidSaveData,
        SchoolDungeonBattleWinnerInvalid,
        SchoolDungeonInvalidReward,
        TimeAttackDungeonDataNotFound = 0x9C40,
        TimeAttackDungeonNotOpen,
        TimeAttackDungeonRoomTimeOut,
        TimeAttackDungeonRoomPlayCountOver,
        TimeAttackDungeonRoomAlreadyExists,
        TimeAttackDungeonRoomAlreadyClosed,
        TimeAttackDungeonRoomNotExist,
        TimeAttackDungeonInvalidRequest,
        TimeAttackDungeonInvalidData,
        WorldRaidDataNotFound = 0xA028,
        WorldRaidSeasonNotOpen,
        WorldRaidBossGroupNotOpen,
        WorldRaidInvalidOpenCondition,
        WorldRaidDifficultyNotOpen,
        WorldRaidAssistCharacterLimitOver,
        WorldRaidContainBlackListCharacter,
        WorldRaidValidFixedEchelonSetting,
        WorldRaidAlredayReceiveRewardAll,
        WorldRaidCannotReceiveReward,
        WorldRaidBossAlreadyDead,
        WorldRaidNotAnotherBossKilled,
        WorldRaidBattleResultUpdateFailed,
        WorldRaidGemEnterCountLimitOver,
        WorldRaidCannotGemEnter,
        WorldRaidNeedClearScenarioBoss,
        WorldRaidBossIsAlive,
        ConquestDataNotFound = 0xA410,
        ConquestAlreadyConquested,
        ConquestNotFullyConquested,
        ConquestStepNotOpened,
        ConquestUnableToReach,
        ConquestUnableToAttack,
        ConquestEchelonChangedCountMax,
        ConquestEchelonNotFound,
        ConquestCharacterAlreadyDeployed,
        ConquestMaxUpgrade,
        ConquestUnitNotFound,
        ConquestObjectNotFound,
        ConquestCalculateRewardNotFound,
        ConquestInvalidTileType,
        ConquestInvalidObjectType,
        ConquestInvalidSaveData,
        ConquestMaxAssistCountReached,
        ConquestErosionConditionNotSatisfied,
        ConquestAdditionalContentNotInUse,
        ConquestCannotUseManageEchelon,
        FriendUserIsNotFriend = 0xA7F8,
        FriendFailedToCreateFriendIdCard,
        FriendRequestNotFound,
        FriendInvalidFriendCode,
        FriendAlreadyFriend,
        FriendMaxSentRequestReached,
        FriendMaxReceivedRequestReached,
        FriendCannotRequestMaxFriendCountReached,
        FriendCannotAcceptMaxFriendCountReached,
        FriendOpponentMaxFriendCountReached,
        FriendTargetIsBusy,
        FriendRequestTargetIsYourself,
        FriendSearchTargetIsYourself,
        FriendInvalidBackgroundId,
        FriendIdCardCommentLengthOverLimit,
        FriendBackgroundNotOwned,
        FriendBlockTargetIsYourself,
        FriendBlockTargetIsAlreadyBlocked,
        FriendBlockTargetIsExceedMaxCount,
        FriendBlockUserCannotOpenProfile,
        FriendBlockUserCannotSendRequest,
        EliminateStageIsNotOpened = 0xABE0,
        MultiSweepPresetDocumentNotFound = 0xAFC8,
        MultiSweepPresetNameEmpty,
        MultiSweepPresetInvalidStageId,
        MultiSweepPresetInvalidId,
        MultiSweepPresetNameInvalidLength,
        MultiSweepPresetTooManySelectStageId,
        MultiSweepPresetInvalidSweepCount,
        EmblemDataNotFound = 0xB3B0,
        EmblemAttachFailed,
        EmblemCannotReceive,
        EmblemPassCheckEmblemIsEmpty,
        StickerDataNotFound = 0xB798,
        StickerNotAcquired,
        StickerDocumentNotFound,
        StickerAlreadyUsed,
        ClearDeckInvalidKey = 0xBB80,
        ClearDeckOutOfDate,
        FieldDataNotFound = 0xEA60,
        FieldInteracionFailed,
        FieldQuestClearFailed,
        FieldInvalidSceneChangedRequest,
        FieldInvalidEndDateRequest,
        FieldCreateDailyQuestFailed,
        FieldResetReplayFailed,
        FieldIncreaseMasteryFailed,
        FieldStageDataInvalid,
        FieldStageEnterFail,
        FieldContentIsClosed,
        FieldEventStageNotCleared,
        MultiFloorRaidSeasonNotOpened = 0xBF68,
        MultiFloorRaidDataNotFound,
        MultiFloorRaidAssistCharacterLimitOver,
        MultiFloorRaidStageOpenConditionFail,
        MultiFloorRaidInvalidSummary,
        MultiFloorRaidInvalidRewardRequest
    }
}
