// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterIllustCoordinateExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static CharacterIllustCoordinateExcel GetRootAsCharacterIllustCoordinateExcel(ByteBuffer _bb) { return GetRootAsCharacterIllustCoordinateExcel(_bb, new CharacterIllustCoordinateExcel()); }
  public static CharacterIllustCoordinateExcel GetRootAsCharacterIllustCoordinateExcel(ByteBuffer _bb, CharacterIllustCoordinateExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterIllustCoordinateExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public float CharacterBodyCenterX { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CharacterBodyCenterY { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float DefaultScale { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MinScale { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float MaxScale { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<FlatData.CharacterIllustCoordinateExcel> CreateCharacterIllustCoordinateExcel(FlatBufferBuilder builder,
      long Id = 0,
      float CharacterBodyCenterX = 0.0f,
      float CharacterBodyCenterY = 0.0f,
      float DefaultScale = 0.0f,
      float MinScale = 0.0f,
      float MaxScale = 0.0f) {
    builder.StartTable(6);
    CharacterIllustCoordinateExcel.AddId(builder, Id);
    CharacterIllustCoordinateExcel.AddMaxScale(builder, MaxScale);
    CharacterIllustCoordinateExcel.AddMinScale(builder, MinScale);
    CharacterIllustCoordinateExcel.AddDefaultScale(builder, DefaultScale);
    CharacterIllustCoordinateExcel.AddCharacterBodyCenterY(builder, CharacterBodyCenterY);
    CharacterIllustCoordinateExcel.AddCharacterBodyCenterX(builder, CharacterBodyCenterX);
    return CharacterIllustCoordinateExcel.EndCharacterIllustCoordinateExcel(builder);
  }

  public static void StartCharacterIllustCoordinateExcel(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddCharacterBodyCenterX(FlatBufferBuilder builder, float characterBodyCenterX) { builder.AddFloat(1, characterBodyCenterX, 0.0f); }
  public static void AddCharacterBodyCenterY(FlatBufferBuilder builder, float characterBodyCenterY) { builder.AddFloat(2, characterBodyCenterY, 0.0f); }
  public static void AddDefaultScale(FlatBufferBuilder builder, float defaultScale) { builder.AddFloat(3, defaultScale, 0.0f); }
  public static void AddMinScale(FlatBufferBuilder builder, float minScale) { builder.AddFloat(4, minScale, 0.0f); }
  public static void AddMaxScale(FlatBufferBuilder builder, float maxScale) { builder.AddFloat(5, maxScale, 0.0f); }
  public static Offset<FlatData.CharacterIllustCoordinateExcel> EndCharacterIllustCoordinateExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterIllustCoordinateExcel>(o);
  }
  public CharacterIllustCoordinateExcelT UnPack() {
    var _o = new CharacterIllustCoordinateExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterIllustCoordinateExcelT _o) {
    _o.Id = this.Id;
    _o.CharacterBodyCenterX = this.CharacterBodyCenterX;
    _o.CharacterBodyCenterY = this.CharacterBodyCenterY;
    _o.DefaultScale = this.DefaultScale;
    _o.MinScale = this.MinScale;
    _o.MaxScale = this.MaxScale;
  }
  public static Offset<FlatData.CharacterIllustCoordinateExcel> Pack(FlatBufferBuilder builder, CharacterIllustCoordinateExcelT _o) {
    if (_o == null) return default(Offset<FlatData.CharacterIllustCoordinateExcel>);
    return CreateCharacterIllustCoordinateExcel(
      builder,
      _o.Id,
      _o.CharacterBodyCenterX,
      _o.CharacterBodyCenterY,
      _o.DefaultScale,
      _o.MinScale,
      _o.MaxScale);
  }
}

public class CharacterIllustCoordinateExcelT
{
  [Newtonsoft.Json.JsonProperty("Id")]
  public long Id { get; set; }
  [Newtonsoft.Json.JsonProperty("CharacterBodyCenterX")]
  public float CharacterBodyCenterX { get; set; }
  [Newtonsoft.Json.JsonProperty("CharacterBodyCenterY")]
  public float CharacterBodyCenterY { get; set; }
  [Newtonsoft.Json.JsonProperty("DefaultScale")]
  public float DefaultScale { get; set; }
  [Newtonsoft.Json.JsonProperty("MinScale")]
  public float MinScale { get; set; }
  [Newtonsoft.Json.JsonProperty("MaxScale")]
  public float MaxScale { get; set; }

  public CharacterIllustCoordinateExcelT() {
    this.Id = 0;
    this.CharacterBodyCenterX = 0.0f;
    this.CharacterBodyCenterY = 0.0f;
    this.DefaultScale = 0.0f;
    this.MinScale = 0.0f;
    this.MaxScale = 0.0f;
  }
}


static public class CharacterIllustCoordinateExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*CharacterBodyCenterX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*CharacterBodyCenterY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*DefaultScale*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*MinScale*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*MaxScale*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
