// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb) { return GetRootAsCharacterExcel(_bb, new CharacterExcel()); }
  public static CharacterExcel GetRootAsCharacterExcel(ByteBuffer _bb, CharacterExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string DevName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDevNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetDevNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetDevNameArray() { return __p.__vector_as_array<byte>(6); }
  public long CostumeGroupId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool IsPlayable { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FlatData.ProductionStep ProductionStep { get { int o = __p.__offset(12); return o != 0 ? (FlatData.ProductionStep)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ProductionStep.ToDo; } }
  public bool CollectionVisible { get { int o = __p.__offset(14); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string ReleaseDate { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetReleaseDateBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetReleaseDateBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetReleaseDateArray() { return __p.__vector_as_array<byte>(16); }
  public string CollectionVisibleStartDate { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleStartDateBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleStartDateBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetCollectionVisibleStartDateArray() { return __p.__vector_as_array<byte>(18); }
  public string CollectionVisibleEndDate { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetCollectionVisibleEndDateBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetCollectionVisibleEndDateBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetCollectionVisibleEndDateArray() { return __p.__vector_as_array<byte>(20); }
  public bool IsPlayableCharacter { get { int o = __p.__offset(22); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public uint LocalizeEtcId { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public FlatData.Rarity Rarity { get { int o = __p.__offset(26); return o != 0 ? (FlatData.Rarity)__p.bb.GetInt(o + __p.bb_pos) : FlatData.Rarity.N; } }
  public bool IsNPC { get { int o = __p.__offset(28); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public FlatData.TacticEntityType TacticEntityType { get { int o = __p.__offset(30); return o != 0 ? (FlatData.TacticEntityType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.TacticEntityType.None; } }
  public bool CanSurvive { get { int o = __p.__offset(32); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsDummy { get { int o = __p.__offset(34); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public int SubPartsCount { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.TacticRole TacticRole { get { int o = __p.__offset(38); return o != 0 ? (FlatData.TacticRole)__p.bb.GetInt(o + __p.bb_pos) : FlatData.TacticRole.None; } }
  public FlatData.WeaponType WeaponType { get { int o = __p.__offset(40); return o != 0 ? (FlatData.WeaponType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.WeaponType.None; } }
  public FlatData.TacticRange TacticRange { get { int o = __p.__offset(42); return o != 0 ? (FlatData.TacticRange)__p.bb.GetInt(o + __p.bb_pos) : FlatData.TacticRange.Back; } }
  public FlatData.BulletType BulletType { get { int o = __p.__offset(44); return o != 0 ? (FlatData.BulletType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.BulletType.Normal; } }
  public FlatData.ArmorType ArmorType { get { int o = __p.__offset(46); return o != 0 ? (FlatData.ArmorType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ArmorType.LightArmor; } }
  public FlatData.AimIKType AimIKType { get { int o = __p.__offset(48); return o != 0 ? (FlatData.AimIKType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.AimIKType.None; } }
  public FlatData.School School { get { int o = __p.__offset(50); return o != 0 ? (FlatData.School)__p.bb.GetInt(o + __p.bb_pos) : FlatData.School.None; } }
  public FlatData.Club Club { get { int o = __p.__offset(52); return o != 0 ? (FlatData.Club)__p.bb.GetInt(o + __p.bb_pos) : FlatData.Club.None; } }
  public int DefaultStarGrade { get { int o = __p.__offset(54); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MaxStarGrade { get { int o = __p.__offset(56); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.StatLevelUpType StatLevelUpType { get { int o = __p.__offset(58); return o != 0 ? (FlatData.StatLevelUpType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.StatLevelUpType.Standard; } }
  public FlatData.SquadType SquadType { get { int o = __p.__offset(60); return o != 0 ? (FlatData.SquadType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.SquadType.None; } }
  public bool Jumpable { get { int o = __p.__offset(62); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long PersonalityId { get { int o = __p.__offset(64); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CharacterAIId { get { int o = __p.__offset(66); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long ExternalBTId { get { int o = __p.__offset(68); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long MainCombatStyleId { get { int o = __p.__offset(70); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CombatStyleIndex { get { int o = __p.__offset(72); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string ScenarioCharacter { get { int o = __p.__offset(74); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetScenarioCharacterBytes() { return __p.__vector_as_span<byte>(74, 1); }
#else
  public ArraySegment<byte>? GetScenarioCharacterBytes() { return __p.__vector_as_arraysegment(74); }
#endif
  public byte[] GetScenarioCharacterArray() { return __p.__vector_as_array<byte>(74); }
  public uint SpawnTemplateId { get { int o = __p.__offset(76); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int FavorLevelupType { get { int o = __p.__offset(78); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.EquipmentCategory EquipmentSlot(int j) { int o = __p.__offset(80); return o != 0 ? (FlatData.EquipmentCategory)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatData.EquipmentCategory)0; }
  public int EquipmentSlotLength { get { int o = __p.__offset(80); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatData.EquipmentCategory> GetEquipmentSlotBytes() { return __p.__vector_as_span<FlatData.EquipmentCategory>(80, 4); }
#else
  public ArraySegment<byte>? GetEquipmentSlotBytes() { return __p.__vector_as_arraysegment(80); }
#endif
  public FlatData.EquipmentCategory[] GetEquipmentSlotArray() { int o = __p.__offset(80); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatData.EquipmentCategory[] a = new FlatData.EquipmentCategory[l]; for (int i = 0; i < l; i++) { a[i] = (FlatData.EquipmentCategory)__p.bb.GetInt(p + i * 4); } return a; }
  public uint WeaponLocalizeId { get { int o = __p.__offset(82); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public bool DisplayEnemyInfo { get { int o = __p.__offset(84); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long BodyRadius { get { int o = __p.__offset(86); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long RandomEffectRadius { get { int o = __p.__offset(88); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool HPBarHide { get { int o = __p.__offset(90); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float HpBarHeight { get { int o = __p.__offset(92); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HighlightFloaterHeight { get { int o = __p.__offset(94); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetX { get { int o = __p.__offset(96); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EmojiOffsetY { get { int o = __p.__offset(98); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int MoveStartFrame { get { int o = __p.__offset(100); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int MoveEndFrame { get { int o = __p.__offset(102); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int JumpMotionFrame { get { int o = __p.__offset(104); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int AppearFrame { get { int o = __p.__offset(106); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool CanMove { get { int o = __p.__offset(108); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanFix { get { int o = __p.__offset(110); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanCrowdControl { get { int o = __p.__offset(112); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool CanBattleItemMove { get { int o = __p.__offset(114); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public bool IsAirUnit { get { int o = __p.__offset(116); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public long AirUnitHeight { get { int o = __p.__offset(118); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.Tag Tags(int j) { int o = __p.__offset(120); return o != 0 ? (FlatData.Tag)__p.bb.GetInt(__p.__vector(o) + j * 4) : (FlatData.Tag)0; }
  public int TagsLength { get { int o = __p.__offset(120); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<FlatData.Tag> GetTagsBytes() { return __p.__vector_as_span<FlatData.Tag>(120, 4); }
#else
  public ArraySegment<byte>? GetTagsBytes() { return __p.__vector_as_arraysegment(120); }
#endif
  public FlatData.Tag[] GetTagsArray() { int o = __p.__offset(120); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); FlatData.Tag[] a = new FlatData.Tag[l]; for (int i = 0; i < l; i++) { a[i] = (FlatData.Tag)__p.bb.GetInt(p + i * 4); } return a; }
  public long SecretStoneItemId { get { int o = __p.__offset(122); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int SecretStoneItemAmount { get { int o = __p.__offset(124); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CharacterPieceItemId { get { int o = __p.__offset(126); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int CharacterPieceItemAmount { get { int o = __p.__offset(128); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long CombineRecipeId { get { int o = __p.__offset(130); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.CharacterExcel> CreateCharacterExcel(FlatBufferBuilder builder,
      long Id = 0,
      StringOffset DevNameOffset = default(StringOffset),
      long CostumeGroupId = 0,
      bool IsPlayable = false,
      FlatData.ProductionStep ProductionStep = FlatData.ProductionStep.ToDo,
      bool CollectionVisible = false,
      StringOffset ReleaseDateOffset = default(StringOffset),
      StringOffset CollectionVisibleStartDateOffset = default(StringOffset),
      StringOffset CollectionVisibleEndDateOffset = default(StringOffset),
      bool IsPlayableCharacter = false,
      uint LocalizeEtcId = 0,
      FlatData.Rarity Rarity = FlatData.Rarity.N,
      bool IsNPC = false,
      FlatData.TacticEntityType TacticEntityType = FlatData.TacticEntityType.None,
      bool CanSurvive = false,
      bool IsDummy = false,
      int SubPartsCount = 0,
      FlatData.TacticRole TacticRole = FlatData.TacticRole.None,
      FlatData.WeaponType WeaponType = FlatData.WeaponType.None,
      FlatData.TacticRange TacticRange = FlatData.TacticRange.Back,
      FlatData.BulletType BulletType = FlatData.BulletType.Normal,
      FlatData.ArmorType ArmorType = FlatData.ArmorType.LightArmor,
      FlatData.AimIKType AimIKType = FlatData.AimIKType.None,
      FlatData.School School = FlatData.School.None,
      FlatData.Club Club = FlatData.Club.None,
      int DefaultStarGrade = 0,
      int MaxStarGrade = 0,
      FlatData.StatLevelUpType StatLevelUpType = FlatData.StatLevelUpType.Standard,
      FlatData.SquadType SquadType = FlatData.SquadType.None,
      bool Jumpable = false,
      long PersonalityId = 0,
      long CharacterAIId = 0,
      long ExternalBTId = 0,
      long MainCombatStyleId = 0,
      int CombatStyleIndex = 0,
      StringOffset ScenarioCharacterOffset = default(StringOffset),
      uint SpawnTemplateId = 0,
      int FavorLevelupType = 0,
      VectorOffset EquipmentSlotOffset = default(VectorOffset),
      uint WeaponLocalizeId = 0,
      bool DisplayEnemyInfo = false,
      long BodyRadius = 0,
      long RandomEffectRadius = 0,
      bool HPBarHide = false,
      float HpBarHeight = 0.0f,
      float HighlightFloaterHeight = 0.0f,
      float EmojiOffsetX = 0.0f,
      float EmojiOffsetY = 0.0f,
      int MoveStartFrame = 0,
      int MoveEndFrame = 0,
      int JumpMotionFrame = 0,
      int AppearFrame = 0,
      bool CanMove = false,
      bool CanFix = false,
      bool CanCrowdControl = false,
      bool CanBattleItemMove = false,
      bool IsAirUnit = false,
      long AirUnitHeight = 0,
      VectorOffset TagsOffset = default(VectorOffset),
      long SecretStoneItemId = 0,
      int SecretStoneItemAmount = 0,
      long CharacterPieceItemId = 0,
      int CharacterPieceItemAmount = 0,
      long CombineRecipeId = 0) {
    builder.StartTable(64);
    CharacterExcel.AddCombineRecipeId(builder, CombineRecipeId);
    CharacterExcel.AddCharacterPieceItemId(builder, CharacterPieceItemId);
    CharacterExcel.AddSecretStoneItemId(builder, SecretStoneItemId);
    CharacterExcel.AddAirUnitHeight(builder, AirUnitHeight);
    CharacterExcel.AddRandomEffectRadius(builder, RandomEffectRadius);
    CharacterExcel.AddBodyRadius(builder, BodyRadius);
    CharacterExcel.AddMainCombatStyleId(builder, MainCombatStyleId);
    CharacterExcel.AddExternalBTId(builder, ExternalBTId);
    CharacterExcel.AddCharacterAIId(builder, CharacterAIId);
    CharacterExcel.AddPersonalityId(builder, PersonalityId);
    CharacterExcel.AddCostumeGroupId(builder, CostumeGroupId);
    CharacterExcel.AddId(builder, Id);
    CharacterExcel.AddCharacterPieceItemAmount(builder, CharacterPieceItemAmount);
    CharacterExcel.AddSecretStoneItemAmount(builder, SecretStoneItemAmount);
    CharacterExcel.AddTags(builder, TagsOffset);
    CharacterExcel.AddAppearFrame(builder, AppearFrame);
    CharacterExcel.AddJumpMotionFrame(builder, JumpMotionFrame);
    CharacterExcel.AddMoveEndFrame(builder, MoveEndFrame);
    CharacterExcel.AddMoveStartFrame(builder, MoveStartFrame);
    CharacterExcel.AddEmojiOffsetY(builder, EmojiOffsetY);
    CharacterExcel.AddEmojiOffsetX(builder, EmojiOffsetX);
    CharacterExcel.AddHighlightFloaterHeight(builder, HighlightFloaterHeight);
    CharacterExcel.AddHpBarHeight(builder, HpBarHeight);
    CharacterExcel.AddWeaponLocalizeId(builder, WeaponLocalizeId);
    CharacterExcel.AddEquipmentSlot(builder, EquipmentSlotOffset);
    CharacterExcel.AddFavorLevelupType(builder, FavorLevelupType);
    CharacterExcel.AddSpawnTemplateId(builder, SpawnTemplateId);
    CharacterExcel.AddScenarioCharacter(builder, ScenarioCharacterOffset);
    CharacterExcel.AddCombatStyleIndex(builder, CombatStyleIndex);
    CharacterExcel.AddSquadType(builder, SquadType);
    CharacterExcel.AddStatLevelUpType(builder, StatLevelUpType);
    CharacterExcel.AddMaxStarGrade(builder, MaxStarGrade);
    CharacterExcel.AddDefaultStarGrade(builder, DefaultStarGrade);
    CharacterExcel.AddClub(builder, Club);
    CharacterExcel.AddSchool(builder, School);
    CharacterExcel.AddAimIKType(builder, AimIKType);
    CharacterExcel.AddArmorType(builder, ArmorType);
    CharacterExcel.AddBulletType(builder, BulletType);
    CharacterExcel.AddTacticRange(builder, TacticRange);
    CharacterExcel.AddWeaponType(builder, WeaponType);
    CharacterExcel.AddTacticRole(builder, TacticRole);
    CharacterExcel.AddSubPartsCount(builder, SubPartsCount);
    CharacterExcel.AddTacticEntityType(builder, TacticEntityType);
    CharacterExcel.AddRarity(builder, Rarity);
    CharacterExcel.AddLocalizeEtcId(builder, LocalizeEtcId);
    CharacterExcel.AddCollectionVisibleEndDate(builder, CollectionVisibleEndDateOffset);
    CharacterExcel.AddCollectionVisibleStartDate(builder, CollectionVisibleStartDateOffset);
    CharacterExcel.AddReleaseDate(builder, ReleaseDateOffset);
    CharacterExcel.AddProductionStep(builder, ProductionStep);
    CharacterExcel.AddDevName(builder, DevNameOffset);
    CharacterExcel.AddIsAirUnit(builder, IsAirUnit);
    CharacterExcel.AddCanBattleItemMove(builder, CanBattleItemMove);
    CharacterExcel.AddCanCrowdControl(builder, CanCrowdControl);
    CharacterExcel.AddCanFix(builder, CanFix);
    CharacterExcel.AddCanMove(builder, CanMove);
    CharacterExcel.AddHPBarHide(builder, HPBarHide);
    CharacterExcel.AddDisplayEnemyInfo(builder, DisplayEnemyInfo);
    CharacterExcel.AddJumpable(builder, Jumpable);
    CharacterExcel.AddIsDummy(builder, IsDummy);
    CharacterExcel.AddCanSurvive(builder, CanSurvive);
    CharacterExcel.AddIsNPC(builder, IsNPC);
    CharacterExcel.AddIsPlayableCharacter(builder, IsPlayableCharacter);
    CharacterExcel.AddCollectionVisible(builder, CollectionVisible);
    CharacterExcel.AddIsPlayable(builder, IsPlayable);
    return CharacterExcel.EndCharacterExcel(builder);
  }

  public static void StartCharacterExcel(FlatBufferBuilder builder) { builder.StartTable(64); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddDevName(FlatBufferBuilder builder, StringOffset devNameOffset) { builder.AddOffset(1, devNameOffset.Value, 0); }
  public static void AddCostumeGroupId(FlatBufferBuilder builder, long costumeGroupId) { builder.AddLong(2, costumeGroupId, 0); }
  public static void AddIsPlayable(FlatBufferBuilder builder, bool isPlayable) { builder.AddBool(3, isPlayable, false); }
  public static void AddProductionStep(FlatBufferBuilder builder, FlatData.ProductionStep productionStep) { builder.AddInt(4, (int)productionStep, 0); }
  public static void AddCollectionVisible(FlatBufferBuilder builder, bool collectionVisible) { builder.AddBool(5, collectionVisible, false); }
  public static void AddReleaseDate(FlatBufferBuilder builder, StringOffset releaseDateOffset) { builder.AddOffset(6, releaseDateOffset.Value, 0); }
  public static void AddCollectionVisibleStartDate(FlatBufferBuilder builder, StringOffset collectionVisibleStartDateOffset) { builder.AddOffset(7, collectionVisibleStartDateOffset.Value, 0); }
  public static void AddCollectionVisibleEndDate(FlatBufferBuilder builder, StringOffset collectionVisibleEndDateOffset) { builder.AddOffset(8, collectionVisibleEndDateOffset.Value, 0); }
  public static void AddIsPlayableCharacter(FlatBufferBuilder builder, bool isPlayableCharacter) { builder.AddBool(9, isPlayableCharacter, false); }
  public static void AddLocalizeEtcId(FlatBufferBuilder builder, uint localizeEtcId) { builder.AddUint(10, localizeEtcId, 0); }
  public static void AddRarity(FlatBufferBuilder builder, FlatData.Rarity rarity) { builder.AddInt(11, (int)rarity, 0); }
  public static void AddIsNPC(FlatBufferBuilder builder, bool isNPC) { builder.AddBool(12, isNPC, false); }
  public static void AddTacticEntityType(FlatBufferBuilder builder, FlatData.TacticEntityType tacticEntityType) { builder.AddInt(13, (int)tacticEntityType, 0); }
  public static void AddCanSurvive(FlatBufferBuilder builder, bool canSurvive) { builder.AddBool(14, canSurvive, false); }
  public static void AddIsDummy(FlatBufferBuilder builder, bool isDummy) { builder.AddBool(15, isDummy, false); }
  public static void AddSubPartsCount(FlatBufferBuilder builder, int subPartsCount) { builder.AddInt(16, subPartsCount, 0); }
  public static void AddTacticRole(FlatBufferBuilder builder, FlatData.TacticRole tacticRole) { builder.AddInt(17, (int)tacticRole, 0); }
  public static void AddWeaponType(FlatBufferBuilder builder, FlatData.WeaponType weaponType) { builder.AddInt(18, (int)weaponType, 0); }
  public static void AddTacticRange(FlatBufferBuilder builder, FlatData.TacticRange tacticRange) { builder.AddInt(19, (int)tacticRange, 0); }
  public static void AddBulletType(FlatBufferBuilder builder, FlatData.BulletType bulletType) { builder.AddInt(20, (int)bulletType, 0); }
  public static void AddArmorType(FlatBufferBuilder builder, FlatData.ArmorType armorType) { builder.AddInt(21, (int)armorType, 0); }
  public static void AddAimIKType(FlatBufferBuilder builder, FlatData.AimIKType aimIKType) { builder.AddInt(22, (int)aimIKType, 0); }
  public static void AddSchool(FlatBufferBuilder builder, FlatData.School school) { builder.AddInt(23, (int)school, 0); }
  public static void AddClub(FlatBufferBuilder builder, FlatData.Club club) { builder.AddInt(24, (int)club, 0); }
  public static void AddDefaultStarGrade(FlatBufferBuilder builder, int defaultStarGrade) { builder.AddInt(25, defaultStarGrade, 0); }
  public static void AddMaxStarGrade(FlatBufferBuilder builder, int maxStarGrade) { builder.AddInt(26, maxStarGrade, 0); }
  public static void AddStatLevelUpType(FlatBufferBuilder builder, FlatData.StatLevelUpType statLevelUpType) { builder.AddInt(27, (int)statLevelUpType, 0); }
  public static void AddSquadType(FlatBufferBuilder builder, FlatData.SquadType squadType) { builder.AddInt(28, (int)squadType, 0); }
  public static void AddJumpable(FlatBufferBuilder builder, bool jumpable) { builder.AddBool(29, jumpable, false); }
  public static void AddPersonalityId(FlatBufferBuilder builder, long personalityId) { builder.AddLong(30, personalityId, 0); }
  public static void AddCharacterAIId(FlatBufferBuilder builder, long characterAIId) { builder.AddLong(31, characterAIId, 0); }
  public static void AddExternalBTId(FlatBufferBuilder builder, long externalBTId) { builder.AddLong(32, externalBTId, 0); }
  public static void AddMainCombatStyleId(FlatBufferBuilder builder, long mainCombatStyleId) { builder.AddLong(33, mainCombatStyleId, 0); }
  public static void AddCombatStyleIndex(FlatBufferBuilder builder, int combatStyleIndex) { builder.AddInt(34, combatStyleIndex, 0); }
  public static void AddScenarioCharacter(FlatBufferBuilder builder, StringOffset scenarioCharacterOffset) { builder.AddOffset(35, scenarioCharacterOffset.Value, 0); }
  public static void AddSpawnTemplateId(FlatBufferBuilder builder, uint spawnTemplateId) { builder.AddUint(36, spawnTemplateId, 0); }
  public static void AddFavorLevelupType(FlatBufferBuilder builder, int favorLevelupType) { builder.AddInt(37, favorLevelupType, 0); }
  public static void AddEquipmentSlot(FlatBufferBuilder builder, VectorOffset equipmentSlotOffset) { builder.AddOffset(38, equipmentSlotOffset.Value, 0); }
  public static VectorOffset CreateEquipmentSlotVector(FlatBufferBuilder builder, FlatData.EquipmentCategory[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, FlatData.EquipmentCategory[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatData.EquipmentCategory> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEquipmentSlotVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatData.EquipmentCategory>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEquipmentSlotVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWeaponLocalizeId(FlatBufferBuilder builder, uint weaponLocalizeId) { builder.AddUint(39, weaponLocalizeId, 0); }
  public static void AddDisplayEnemyInfo(FlatBufferBuilder builder, bool displayEnemyInfo) { builder.AddBool(40, displayEnemyInfo, false); }
  public static void AddBodyRadius(FlatBufferBuilder builder, long bodyRadius) { builder.AddLong(41, bodyRadius, 0); }
  public static void AddRandomEffectRadius(FlatBufferBuilder builder, long randomEffectRadius) { builder.AddLong(42, randomEffectRadius, 0); }
  public static void AddHPBarHide(FlatBufferBuilder builder, bool hPBarHide) { builder.AddBool(43, hPBarHide, false); }
  public static void AddHpBarHeight(FlatBufferBuilder builder, float hpBarHeight) { builder.AddFloat(44, hpBarHeight, 0.0f); }
  public static void AddHighlightFloaterHeight(FlatBufferBuilder builder, float highlightFloaterHeight) { builder.AddFloat(45, highlightFloaterHeight, 0.0f); }
  public static void AddEmojiOffsetX(FlatBufferBuilder builder, float emojiOffsetX) { builder.AddFloat(46, emojiOffsetX, 0.0f); }
  public static void AddEmojiOffsetY(FlatBufferBuilder builder, float emojiOffsetY) { builder.AddFloat(47, emojiOffsetY, 0.0f); }
  public static void AddMoveStartFrame(FlatBufferBuilder builder, int moveStartFrame) { builder.AddInt(48, moveStartFrame, 0); }
  public static void AddMoveEndFrame(FlatBufferBuilder builder, int moveEndFrame) { builder.AddInt(49, moveEndFrame, 0); }
  public static void AddJumpMotionFrame(FlatBufferBuilder builder, int jumpMotionFrame) { builder.AddInt(50, jumpMotionFrame, 0); }
  public static void AddAppearFrame(FlatBufferBuilder builder, int appearFrame) { builder.AddInt(51, appearFrame, 0); }
  public static void AddCanMove(FlatBufferBuilder builder, bool canMove) { builder.AddBool(52, canMove, false); }
  public static void AddCanFix(FlatBufferBuilder builder, bool canFix) { builder.AddBool(53, canFix, false); }
  public static void AddCanCrowdControl(FlatBufferBuilder builder, bool canCrowdControl) { builder.AddBool(54, canCrowdControl, false); }
  public static void AddCanBattleItemMove(FlatBufferBuilder builder, bool canBattleItemMove) { builder.AddBool(55, canBattleItemMove, false); }
  public static void AddIsAirUnit(FlatBufferBuilder builder, bool isAirUnit) { builder.AddBool(56, isAirUnit, false); }
  public static void AddAirUnitHeight(FlatBufferBuilder builder, long airUnitHeight) { builder.AddLong(57, airUnitHeight, 0); }
  public static void AddTags(FlatBufferBuilder builder, VectorOffset tagsOffset) { builder.AddOffset(58, tagsOffset.Value, 0); }
  public static VectorOffset CreateTagsVector(FlatBufferBuilder builder, FlatData.Tag[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, FlatData.Tag[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, ArraySegment<FlatData.Tag> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateTagsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<FlatData.Tag>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartTagsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddSecretStoneItemId(FlatBufferBuilder builder, long secretStoneItemId) { builder.AddLong(59, secretStoneItemId, 0); }
  public static void AddSecretStoneItemAmount(FlatBufferBuilder builder, int secretStoneItemAmount) { builder.AddInt(60, secretStoneItemAmount, 0); }
  public static void AddCharacterPieceItemId(FlatBufferBuilder builder, long characterPieceItemId) { builder.AddLong(61, characterPieceItemId, 0); }
  public static void AddCharacterPieceItemAmount(FlatBufferBuilder builder, int characterPieceItemAmount) { builder.AddInt(62, characterPieceItemAmount, 0); }
  public static void AddCombineRecipeId(FlatBufferBuilder builder, long combineRecipeId) { builder.AddLong(63, combineRecipeId, 0); }
  public static Offset<FlatData.CharacterExcel> EndCharacterExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.CharacterExcel>(o);
  }
  public CharacterExcelT UnPack() {
    var _o = new CharacterExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(CharacterExcelT _o) {
    _o.Id = this.Id;
    _o.DevName = this.DevName;
    _o.CostumeGroupId = this.CostumeGroupId;
    _o.IsPlayable = this.IsPlayable;
    _o.ProductionStep = this.ProductionStep;
    _o.CollectionVisible = this.CollectionVisible;
    _o.ReleaseDate = this.ReleaseDate;
    _o.CollectionVisibleStartDate = this.CollectionVisibleStartDate;
    _o.CollectionVisibleEndDate = this.CollectionVisibleEndDate;
    _o.IsPlayableCharacter = this.IsPlayableCharacter;
    _o.LocalizeEtcId = this.LocalizeEtcId;
    _o.Rarity = this.Rarity;
    _o.IsNPC = this.IsNPC;
    _o.TacticEntityType = this.TacticEntityType;
    _o.CanSurvive = this.CanSurvive;
    _o.IsDummy = this.IsDummy;
    _o.SubPartsCount = this.SubPartsCount;
    _o.TacticRole = this.TacticRole;
    _o.WeaponType = this.WeaponType;
    _o.TacticRange = this.TacticRange;
    _o.BulletType = this.BulletType;
    _o.ArmorType = this.ArmorType;
    _o.AimIKType = this.AimIKType;
    _o.School = this.School;
    _o.Club = this.Club;
    _o.DefaultStarGrade = this.DefaultStarGrade;
    _o.MaxStarGrade = this.MaxStarGrade;
    _o.StatLevelUpType = this.StatLevelUpType;
    _o.SquadType = this.SquadType;
    _o.Jumpable = this.Jumpable;
    _o.PersonalityId = this.PersonalityId;
    _o.CharacterAIId = this.CharacterAIId;
    _o.ExternalBTId = this.ExternalBTId;
    _o.MainCombatStyleId = this.MainCombatStyleId;
    _o.CombatStyleIndex = this.CombatStyleIndex;
    _o.ScenarioCharacter = this.ScenarioCharacter;
    _o.SpawnTemplateId = this.SpawnTemplateId;
    _o.FavorLevelupType = this.FavorLevelupType;
    _o.EquipmentSlot = new List<FlatData.EquipmentCategory>();
    for (var _j = 0; _j < this.EquipmentSlotLength; ++_j) {_o.EquipmentSlot.Add(this.EquipmentSlot(_j));}
    _o.WeaponLocalizeId = this.WeaponLocalizeId;
    _o.DisplayEnemyInfo = this.DisplayEnemyInfo;
    _o.BodyRadius = this.BodyRadius;
    _o.RandomEffectRadius = this.RandomEffectRadius;
    _o.HPBarHide = this.HPBarHide;
    _o.HpBarHeight = this.HpBarHeight;
    _o.HighlightFloaterHeight = this.HighlightFloaterHeight;
    _o.EmojiOffsetX = this.EmojiOffsetX;
    _o.EmojiOffsetY = this.EmojiOffsetY;
    _o.MoveStartFrame = this.MoveStartFrame;
    _o.MoveEndFrame = this.MoveEndFrame;
    _o.JumpMotionFrame = this.JumpMotionFrame;
    _o.AppearFrame = this.AppearFrame;
    _o.CanMove = this.CanMove;
    _o.CanFix = this.CanFix;
    _o.CanCrowdControl = this.CanCrowdControl;
    _o.CanBattleItemMove = this.CanBattleItemMove;
    _o.IsAirUnit = this.IsAirUnit;
    _o.AirUnitHeight = this.AirUnitHeight;
    _o.Tags = new List<FlatData.Tag>();
    for (var _j = 0; _j < this.TagsLength; ++_j) {_o.Tags.Add(this.Tags(_j));}
    _o.SecretStoneItemId = this.SecretStoneItemId;
    _o.SecretStoneItemAmount = this.SecretStoneItemAmount;
    _o.CharacterPieceItemId = this.CharacterPieceItemId;
    _o.CharacterPieceItemAmount = this.CharacterPieceItemAmount;
    _o.CombineRecipeId = this.CombineRecipeId;
  }
  public static Offset<FlatData.CharacterExcel> Pack(FlatBufferBuilder builder, CharacterExcelT _o) {
    if (_o == null) return default(Offset<FlatData.CharacterExcel>);
    var _DevName = _o.DevName == null ? default(StringOffset) : builder.CreateString(_o.DevName);
    var _ReleaseDate = _o.ReleaseDate == null ? default(StringOffset) : builder.CreateString(_o.ReleaseDate);
    var _CollectionVisibleStartDate = _o.CollectionVisibleStartDate == null ? default(StringOffset) : builder.CreateString(_o.CollectionVisibleStartDate);
    var _CollectionVisibleEndDate = _o.CollectionVisibleEndDate == null ? default(StringOffset) : builder.CreateString(_o.CollectionVisibleEndDate);
    var _ScenarioCharacter = _o.ScenarioCharacter == null ? default(StringOffset) : builder.CreateString(_o.ScenarioCharacter);
    var _EquipmentSlot = default(VectorOffset);
    if (_o.EquipmentSlot != null) {
      var __EquipmentSlot = _o.EquipmentSlot.ToArray();
      _EquipmentSlot = CreateEquipmentSlotVector(builder, __EquipmentSlot);
    }
    var _Tags = default(VectorOffset);
    if (_o.Tags != null) {
      var __Tags = _o.Tags.ToArray();
      _Tags = CreateTagsVector(builder, __Tags);
    }
    return CreateCharacterExcel(
      builder,
      _o.Id,
      _DevName,
      _o.CostumeGroupId,
      _o.IsPlayable,
      _o.ProductionStep,
      _o.CollectionVisible,
      _ReleaseDate,
      _CollectionVisibleStartDate,
      _CollectionVisibleEndDate,
      _o.IsPlayableCharacter,
      _o.LocalizeEtcId,
      _o.Rarity,
      _o.IsNPC,
      _o.TacticEntityType,
      _o.CanSurvive,
      _o.IsDummy,
      _o.SubPartsCount,
      _o.TacticRole,
      _o.WeaponType,
      _o.TacticRange,
      _o.BulletType,
      _o.ArmorType,
      _o.AimIKType,
      _o.School,
      _o.Club,
      _o.DefaultStarGrade,
      _o.MaxStarGrade,
      _o.StatLevelUpType,
      _o.SquadType,
      _o.Jumpable,
      _o.PersonalityId,
      _o.CharacterAIId,
      _o.ExternalBTId,
      _o.MainCombatStyleId,
      _o.CombatStyleIndex,
      _ScenarioCharacter,
      _o.SpawnTemplateId,
      _o.FavorLevelupType,
      _EquipmentSlot,
      _o.WeaponLocalizeId,
      _o.DisplayEnemyInfo,
      _o.BodyRadius,
      _o.RandomEffectRadius,
      _o.HPBarHide,
      _o.HpBarHeight,
      _o.HighlightFloaterHeight,
      _o.EmojiOffsetX,
      _o.EmojiOffsetY,
      _o.MoveStartFrame,
      _o.MoveEndFrame,
      _o.JumpMotionFrame,
      _o.AppearFrame,
      _o.CanMove,
      _o.CanFix,
      _o.CanCrowdControl,
      _o.CanBattleItemMove,
      _o.IsAirUnit,
      _o.AirUnitHeight,
      _Tags,
      _o.SecretStoneItemId,
      _o.SecretStoneItemAmount,
      _o.CharacterPieceItemId,
      _o.CharacterPieceItemAmount,
      _o.CombineRecipeId);
  }
}

public class CharacterExcelT
{
  [Newtonsoft.Json.JsonProperty("Id")]
  public long Id { get; set; }
  [Newtonsoft.Json.JsonProperty("DevName")]
  public string DevName { get; set; }
  [Newtonsoft.Json.JsonProperty("CostumeGroupId")]
  public long CostumeGroupId { get; set; }
  [Newtonsoft.Json.JsonProperty("IsPlayable")]
  public bool IsPlayable { get; set; }
  [Newtonsoft.Json.JsonProperty("ProductionStep")]
  public FlatData.ProductionStep ProductionStep { get; set; }
  [Newtonsoft.Json.JsonProperty("CollectionVisible")]
  public bool CollectionVisible { get; set; }
  [Newtonsoft.Json.JsonProperty("ReleaseDate")]
  public string ReleaseDate { get; set; }
  [Newtonsoft.Json.JsonProperty("CollectionVisibleStartDate")]
  public string CollectionVisibleStartDate { get; set; }
  [Newtonsoft.Json.JsonProperty("CollectionVisibleEndDate")]
  public string CollectionVisibleEndDate { get; set; }
  [Newtonsoft.Json.JsonProperty("IsPlayableCharacter")]
  public bool IsPlayableCharacter { get; set; }
  [Newtonsoft.Json.JsonProperty("LocalizeEtcId")]
  public uint LocalizeEtcId { get; set; }
  [Newtonsoft.Json.JsonProperty("Rarity")]
  public FlatData.Rarity Rarity { get; set; }
  [Newtonsoft.Json.JsonProperty("IsNPC")]
  public bool IsNPC { get; set; }
  [Newtonsoft.Json.JsonProperty("TacticEntityType")]
  public FlatData.TacticEntityType TacticEntityType { get; set; }
  [Newtonsoft.Json.JsonProperty("CanSurvive")]
  public bool CanSurvive { get; set; }
  [Newtonsoft.Json.JsonProperty("IsDummy")]
  public bool IsDummy { get; set; }
  [Newtonsoft.Json.JsonProperty("SubPartsCount")]
  public int SubPartsCount { get; set; }
  [Newtonsoft.Json.JsonProperty("TacticRole")]
  public FlatData.TacticRole TacticRole { get; set; }
  [Newtonsoft.Json.JsonProperty("WeaponType")]
  public FlatData.WeaponType WeaponType { get; set; }
  [Newtonsoft.Json.JsonProperty("TacticRange")]
  public FlatData.TacticRange TacticRange { get; set; }
  [Newtonsoft.Json.JsonProperty("BulletType")]
  public FlatData.BulletType BulletType { get; set; }
  [Newtonsoft.Json.JsonProperty("ArmorType")]
  public FlatData.ArmorType ArmorType { get; set; }
  [Newtonsoft.Json.JsonProperty("AimIKType")]
  public FlatData.AimIKType AimIKType { get; set; }
  [Newtonsoft.Json.JsonProperty("School")]
  public FlatData.School School { get; set; }
  [Newtonsoft.Json.JsonProperty("Club")]
  public FlatData.Club Club { get; set; }
  [Newtonsoft.Json.JsonProperty("DefaultStarGrade")]
  public int DefaultStarGrade { get; set; }
  [Newtonsoft.Json.JsonProperty("MaxStarGrade")]
  public int MaxStarGrade { get; set; }
  [Newtonsoft.Json.JsonProperty("StatLevelUpType")]
  public FlatData.StatLevelUpType StatLevelUpType { get; set; }
  [Newtonsoft.Json.JsonProperty("SquadType")]
  public FlatData.SquadType SquadType { get; set; }
  [Newtonsoft.Json.JsonProperty("Jumpable")]
  public bool Jumpable { get; set; }
  [Newtonsoft.Json.JsonProperty("PersonalityId")]
  public long PersonalityId { get; set; }
  [Newtonsoft.Json.JsonProperty("CharacterAIId")]
  public long CharacterAIId { get; set; }
  [Newtonsoft.Json.JsonProperty("ExternalBTId")]
  public long ExternalBTId { get; set; }
  [Newtonsoft.Json.JsonProperty("MainCombatStyleId")]
  public long MainCombatStyleId { get; set; }
  [Newtonsoft.Json.JsonProperty("CombatStyleIndex")]
  public int CombatStyleIndex { get; set; }
  [Newtonsoft.Json.JsonProperty("ScenarioCharacter")]
  public string ScenarioCharacter { get; set; }
  [Newtonsoft.Json.JsonProperty("SpawnTemplateId")]
  public uint SpawnTemplateId { get; set; }
  [Newtonsoft.Json.JsonProperty("FavorLevelupType")]
  public int FavorLevelupType { get; set; }
  [Newtonsoft.Json.JsonProperty("EquipmentSlot")]
  public List<FlatData.EquipmentCategory> EquipmentSlot { get; set; }
  [Newtonsoft.Json.JsonProperty("WeaponLocalizeId")]
  public uint WeaponLocalizeId { get; set; }
  [Newtonsoft.Json.JsonProperty("DisplayEnemyInfo")]
  public bool DisplayEnemyInfo { get; set; }
  [Newtonsoft.Json.JsonProperty("BodyRadius")]
  public long BodyRadius { get; set; }
  [Newtonsoft.Json.JsonProperty("RandomEffectRadius")]
  public long RandomEffectRadius { get; set; }
  [Newtonsoft.Json.JsonProperty("HPBarHide")]
  public bool HPBarHide { get; set; }
  [Newtonsoft.Json.JsonProperty("HpBarHeight")]
  public float HpBarHeight { get; set; }
  [Newtonsoft.Json.JsonProperty("HighlightFloaterHeight")]
  public float HighlightFloaterHeight { get; set; }
  [Newtonsoft.Json.JsonProperty("EmojiOffsetX")]
  public float EmojiOffsetX { get; set; }
  [Newtonsoft.Json.JsonProperty("EmojiOffsetY")]
  public float EmojiOffsetY { get; set; }
  [Newtonsoft.Json.JsonProperty("MoveStartFrame")]
  public int MoveStartFrame { get; set; }
  [Newtonsoft.Json.JsonProperty("MoveEndFrame")]
  public int MoveEndFrame { get; set; }
  [Newtonsoft.Json.JsonProperty("JumpMotionFrame")]
  public int JumpMotionFrame { get; set; }
  [Newtonsoft.Json.JsonProperty("AppearFrame")]
  public int AppearFrame { get; set; }
  [Newtonsoft.Json.JsonProperty("CanMove")]
  public bool CanMove { get; set; }
  [Newtonsoft.Json.JsonProperty("CanFix")]
  public bool CanFix { get; set; }
  [Newtonsoft.Json.JsonProperty("CanCrowdControl")]
  public bool CanCrowdControl { get; set; }
  [Newtonsoft.Json.JsonProperty("CanBattleItemMove")]
  public bool CanBattleItemMove { get; set; }
  [Newtonsoft.Json.JsonProperty("IsAirUnit")]
  public bool IsAirUnit { get; set; }
  [Newtonsoft.Json.JsonProperty("AirUnitHeight")]
  public long AirUnitHeight { get; set; }
  [Newtonsoft.Json.JsonProperty("Tags")]
  public List<FlatData.Tag> Tags { get; set; }
  [Newtonsoft.Json.JsonProperty("SecretStoneItemId")]
  public long SecretStoneItemId { get; set; }
  [Newtonsoft.Json.JsonProperty("SecretStoneItemAmount")]
  public int SecretStoneItemAmount { get; set; }
  [Newtonsoft.Json.JsonProperty("CharacterPieceItemId")]
  public long CharacterPieceItemId { get; set; }
  [Newtonsoft.Json.JsonProperty("CharacterPieceItemAmount")]
  public int CharacterPieceItemAmount { get; set; }
  [Newtonsoft.Json.JsonProperty("CombineRecipeId")]
  public long CombineRecipeId { get; set; }

  public CharacterExcelT() {
    this.Id = 0;
    this.DevName = null;
    this.CostumeGroupId = 0;
    this.IsPlayable = false;
    this.ProductionStep = FlatData.ProductionStep.ToDo;
    this.CollectionVisible = false;
    this.ReleaseDate = null;
    this.CollectionVisibleStartDate = null;
    this.CollectionVisibleEndDate = null;
    this.IsPlayableCharacter = false;
    this.LocalizeEtcId = 0;
    this.Rarity = FlatData.Rarity.N;
    this.IsNPC = false;
    this.TacticEntityType = FlatData.TacticEntityType.None;
    this.CanSurvive = false;
    this.IsDummy = false;
    this.SubPartsCount = 0;
    this.TacticRole = FlatData.TacticRole.None;
    this.WeaponType = FlatData.WeaponType.None;
    this.TacticRange = FlatData.TacticRange.Back;
    this.BulletType = FlatData.BulletType.Normal;
    this.ArmorType = FlatData.ArmorType.LightArmor;
    this.AimIKType = FlatData.AimIKType.None;
    this.School = FlatData.School.None;
    this.Club = FlatData.Club.None;
    this.DefaultStarGrade = 0;
    this.MaxStarGrade = 0;
    this.StatLevelUpType = FlatData.StatLevelUpType.Standard;
    this.SquadType = FlatData.SquadType.None;
    this.Jumpable = false;
    this.PersonalityId = 0;
    this.CharacterAIId = 0;
    this.ExternalBTId = 0;
    this.MainCombatStyleId = 0;
    this.CombatStyleIndex = 0;
    this.ScenarioCharacter = null;
    this.SpawnTemplateId = 0;
    this.FavorLevelupType = 0;
    this.EquipmentSlot = null;
    this.WeaponLocalizeId = 0;
    this.DisplayEnemyInfo = false;
    this.BodyRadius = 0;
    this.RandomEffectRadius = 0;
    this.HPBarHide = false;
    this.HpBarHeight = 0.0f;
    this.HighlightFloaterHeight = 0.0f;
    this.EmojiOffsetX = 0.0f;
    this.EmojiOffsetY = 0.0f;
    this.MoveStartFrame = 0;
    this.MoveEndFrame = 0;
    this.JumpMotionFrame = 0;
    this.AppearFrame = 0;
    this.CanMove = false;
    this.CanFix = false;
    this.CanCrowdControl = false;
    this.CanBattleItemMove = false;
    this.IsAirUnit = false;
    this.AirUnitHeight = 0;
    this.Tags = null;
    this.SecretStoneItemId = 0;
    this.SecretStoneItemAmount = 0;
    this.CharacterPieceItemId = 0;
    this.CharacterPieceItemAmount = 0;
    this.CombineRecipeId = 0;
  }
}


static public class CharacterExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*DevName*/, false)
      && verifier.VerifyField(tablePos, 8 /*CostumeGroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*IsPlayable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 12 /*ProductionStep*/, 4 /*FlatData.ProductionStep*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*CollectionVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 16 /*ReleaseDate*/, false)
      && verifier.VerifyString(tablePos, 18 /*CollectionVisibleStartDate*/, false)
      && verifier.VerifyString(tablePos, 20 /*CollectionVisibleEndDate*/, false)
      && verifier.VerifyField(tablePos, 22 /*IsPlayableCharacter*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 24 /*LocalizeEtcId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 26 /*Rarity*/, 4 /*FlatData.Rarity*/, 4, false)
      && verifier.VerifyField(tablePos, 28 /*IsNPC*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 30 /*TacticEntityType*/, 4 /*FlatData.TacticEntityType*/, 4, false)
      && verifier.VerifyField(tablePos, 32 /*CanSurvive*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 34 /*IsDummy*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 36 /*SubPartsCount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 38 /*TacticRole*/, 4 /*FlatData.TacticRole*/, 4, false)
      && verifier.VerifyField(tablePos, 40 /*WeaponType*/, 4 /*FlatData.WeaponType*/, 4, false)
      && verifier.VerifyField(tablePos, 42 /*TacticRange*/, 4 /*FlatData.TacticRange*/, 4, false)
      && verifier.VerifyField(tablePos, 44 /*BulletType*/, 4 /*FlatData.BulletType*/, 4, false)
      && verifier.VerifyField(tablePos, 46 /*ArmorType*/, 4 /*FlatData.ArmorType*/, 4, false)
      && verifier.VerifyField(tablePos, 48 /*AimIKType*/, 4 /*FlatData.AimIKType*/, 4, false)
      && verifier.VerifyField(tablePos, 50 /*School*/, 4 /*FlatData.School*/, 4, false)
      && verifier.VerifyField(tablePos, 52 /*Club*/, 4 /*FlatData.Club*/, 4, false)
      && verifier.VerifyField(tablePos, 54 /*DefaultStarGrade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 56 /*MaxStarGrade*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 58 /*StatLevelUpType*/, 4 /*FlatData.StatLevelUpType*/, 4, false)
      && verifier.VerifyField(tablePos, 60 /*SquadType*/, 4 /*FlatData.SquadType*/, 4, false)
      && verifier.VerifyField(tablePos, 62 /*Jumpable*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 64 /*PersonalityId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 66 /*CharacterAIId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 68 /*ExternalBTId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 70 /*MainCombatStyleId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 72 /*CombatStyleIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 74 /*ScenarioCharacter*/, false)
      && verifier.VerifyField(tablePos, 76 /*SpawnTemplateId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 78 /*FavorLevelupType*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 80 /*EquipmentSlot*/, 4 /*FlatData.EquipmentCategory*/, false)
      && verifier.VerifyField(tablePos, 82 /*WeaponLocalizeId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 84 /*DisplayEnemyInfo*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 86 /*BodyRadius*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 88 /*RandomEffectRadius*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 90 /*HPBarHide*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 92 /*HpBarHeight*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 94 /*HighlightFloaterHeight*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 96 /*EmojiOffsetX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 98 /*EmojiOffsetY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 100 /*MoveStartFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 102 /*MoveEndFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 104 /*JumpMotionFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 106 /*AppearFrame*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 108 /*CanMove*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 110 /*CanFix*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 112 /*CanCrowdControl*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 114 /*CanBattleItemMove*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 116 /*IsAirUnit*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 118 /*AirUnitHeight*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 120 /*Tags*/, 4 /*FlatData.Tag*/, false)
      && verifier.VerifyField(tablePos, 122 /*SecretStoneItemId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 124 /*SecretStoneItemAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 126 /*CharacterPieceItemId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 128 /*CharacterPieceItemAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 130 /*CombineRecipeId*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
