// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ConquestCameraSettingExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ConquestCameraSettingExcel GetRootAsConquestCameraSettingExcel(ByteBuffer _bb) { return GetRootAsConquestCameraSettingExcel(_bb, new ConquestCameraSettingExcel()); }
  public static ConquestCameraSettingExcel GetRootAsConquestCameraSettingExcel(ByteBuffer _bb, ConquestCameraSettingExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ConquestCameraSettingExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public float ConquestMapBoundaryOffsetLeft { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float ConquestMapBoundaryOffsetRight { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float ConquestMapBoundaryOffsetTop { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float ConquestMapBoundaryOffsetBottom { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float ConquestMapCenterOffsetX { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float ConquestMapCenterOffsetY { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CameraAngle { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CameraZoomMax { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CameraZoomMin { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float CameraZoomDefault { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<FlatData.ConquestCameraSettingExcel> CreateConquestCameraSettingExcel(FlatBufferBuilder builder,
      long Id = 0,
      float ConquestMapBoundaryOffsetLeft = 0.0f,
      float ConquestMapBoundaryOffsetRight = 0.0f,
      float ConquestMapBoundaryOffsetTop = 0.0f,
      float ConquestMapBoundaryOffsetBottom = 0.0f,
      float ConquestMapCenterOffsetX = 0.0f,
      float ConquestMapCenterOffsetY = 0.0f,
      float CameraAngle = 0.0f,
      float CameraZoomMax = 0.0f,
      float CameraZoomMin = 0.0f,
      float CameraZoomDefault = 0.0f) {
    builder.StartTable(11);
    ConquestCameraSettingExcel.AddId(builder, Id);
    ConquestCameraSettingExcel.AddCameraZoomDefault(builder, CameraZoomDefault);
    ConquestCameraSettingExcel.AddCameraZoomMin(builder, CameraZoomMin);
    ConquestCameraSettingExcel.AddCameraZoomMax(builder, CameraZoomMax);
    ConquestCameraSettingExcel.AddCameraAngle(builder, CameraAngle);
    ConquestCameraSettingExcel.AddConquestMapCenterOffsetY(builder, ConquestMapCenterOffsetY);
    ConquestCameraSettingExcel.AddConquestMapCenterOffsetX(builder, ConquestMapCenterOffsetX);
    ConquestCameraSettingExcel.AddConquestMapBoundaryOffsetBottom(builder, ConquestMapBoundaryOffsetBottom);
    ConquestCameraSettingExcel.AddConquestMapBoundaryOffsetTop(builder, ConquestMapBoundaryOffsetTop);
    ConquestCameraSettingExcel.AddConquestMapBoundaryOffsetRight(builder, ConquestMapBoundaryOffsetRight);
    ConquestCameraSettingExcel.AddConquestMapBoundaryOffsetLeft(builder, ConquestMapBoundaryOffsetLeft);
    return ConquestCameraSettingExcel.EndConquestCameraSettingExcel(builder);
  }

  public static void StartConquestCameraSettingExcel(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddConquestMapBoundaryOffsetLeft(FlatBufferBuilder builder, float conquestMapBoundaryOffsetLeft) { builder.AddFloat(1, conquestMapBoundaryOffsetLeft, 0.0f); }
  public static void AddConquestMapBoundaryOffsetRight(FlatBufferBuilder builder, float conquestMapBoundaryOffsetRight) { builder.AddFloat(2, conquestMapBoundaryOffsetRight, 0.0f); }
  public static void AddConquestMapBoundaryOffsetTop(FlatBufferBuilder builder, float conquestMapBoundaryOffsetTop) { builder.AddFloat(3, conquestMapBoundaryOffsetTop, 0.0f); }
  public static void AddConquestMapBoundaryOffsetBottom(FlatBufferBuilder builder, float conquestMapBoundaryOffsetBottom) { builder.AddFloat(4, conquestMapBoundaryOffsetBottom, 0.0f); }
  public static void AddConquestMapCenterOffsetX(FlatBufferBuilder builder, float conquestMapCenterOffsetX) { builder.AddFloat(5, conquestMapCenterOffsetX, 0.0f); }
  public static void AddConquestMapCenterOffsetY(FlatBufferBuilder builder, float conquestMapCenterOffsetY) { builder.AddFloat(6, conquestMapCenterOffsetY, 0.0f); }
  public static void AddCameraAngle(FlatBufferBuilder builder, float cameraAngle) { builder.AddFloat(7, cameraAngle, 0.0f); }
  public static void AddCameraZoomMax(FlatBufferBuilder builder, float cameraZoomMax) { builder.AddFloat(8, cameraZoomMax, 0.0f); }
  public static void AddCameraZoomMin(FlatBufferBuilder builder, float cameraZoomMin) { builder.AddFloat(9, cameraZoomMin, 0.0f); }
  public static void AddCameraZoomDefault(FlatBufferBuilder builder, float cameraZoomDefault) { builder.AddFloat(10, cameraZoomDefault, 0.0f); }
  public static Offset<FlatData.ConquestCameraSettingExcel> EndConquestCameraSettingExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.ConquestCameraSettingExcel>(o);
  }
  public ConquestCameraSettingExcelT UnPack() {
    var _o = new ConquestCameraSettingExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ConquestCameraSettingExcelT _o) {
    _o.Id = this.Id;
    _o.ConquestMapBoundaryOffsetLeft = this.ConquestMapBoundaryOffsetLeft;
    _o.ConquestMapBoundaryOffsetRight = this.ConquestMapBoundaryOffsetRight;
    _o.ConquestMapBoundaryOffsetTop = this.ConquestMapBoundaryOffsetTop;
    _o.ConquestMapBoundaryOffsetBottom = this.ConquestMapBoundaryOffsetBottom;
    _o.ConquestMapCenterOffsetX = this.ConquestMapCenterOffsetX;
    _o.ConquestMapCenterOffsetY = this.ConquestMapCenterOffsetY;
    _o.CameraAngle = this.CameraAngle;
    _o.CameraZoomMax = this.CameraZoomMax;
    _o.CameraZoomMin = this.CameraZoomMin;
    _o.CameraZoomDefault = this.CameraZoomDefault;
  }
  public static Offset<FlatData.ConquestCameraSettingExcel> Pack(FlatBufferBuilder builder, ConquestCameraSettingExcelT _o) {
    if (_o == null) return default(Offset<FlatData.ConquestCameraSettingExcel>);
    return CreateConquestCameraSettingExcel(
      builder,
      _o.Id,
      _o.ConquestMapBoundaryOffsetLeft,
      _o.ConquestMapBoundaryOffsetRight,
      _o.ConquestMapBoundaryOffsetTop,
      _o.ConquestMapBoundaryOffsetBottom,
      _o.ConquestMapCenterOffsetX,
      _o.ConquestMapCenterOffsetY,
      _o.CameraAngle,
      _o.CameraZoomMax,
      _o.CameraZoomMin,
      _o.CameraZoomDefault);
  }
}

public class ConquestCameraSettingExcelT
{
  [Newtonsoft.Json.JsonProperty("Id")]
  public long Id { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapBoundaryOffsetLeft")]
  public float ConquestMapBoundaryOffsetLeft { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapBoundaryOffsetRight")]
  public float ConquestMapBoundaryOffsetRight { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapBoundaryOffsetTop")]
  public float ConquestMapBoundaryOffsetTop { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapBoundaryOffsetBottom")]
  public float ConquestMapBoundaryOffsetBottom { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapCenterOffsetX")]
  public float ConquestMapCenterOffsetX { get; set; }
  [Newtonsoft.Json.JsonProperty("ConquestMapCenterOffsetY")]
  public float ConquestMapCenterOffsetY { get; set; }
  [Newtonsoft.Json.JsonProperty("CameraAngle")]
  public float CameraAngle { get; set; }
  [Newtonsoft.Json.JsonProperty("CameraZoomMax")]
  public float CameraZoomMax { get; set; }
  [Newtonsoft.Json.JsonProperty("CameraZoomMin")]
  public float CameraZoomMin { get; set; }
  [Newtonsoft.Json.JsonProperty("CameraZoomDefault")]
  public float CameraZoomDefault { get; set; }

  public ConquestCameraSettingExcelT() {
    this.Id = 0;
    this.ConquestMapBoundaryOffsetLeft = 0.0f;
    this.ConquestMapBoundaryOffsetRight = 0.0f;
    this.ConquestMapBoundaryOffsetTop = 0.0f;
    this.ConquestMapBoundaryOffsetBottom = 0.0f;
    this.ConquestMapCenterOffsetX = 0.0f;
    this.ConquestMapCenterOffsetY = 0.0f;
    this.CameraAngle = 0.0f;
    this.CameraZoomMax = 0.0f;
    this.CameraZoomMin = 0.0f;
    this.CameraZoomDefault = 0.0f;
  }
}


static public class ConquestCameraSettingExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*ConquestMapBoundaryOffsetLeft*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*ConquestMapBoundaryOffsetRight*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*ConquestMapBoundaryOffsetTop*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*ConquestMapBoundaryOffsetBottom*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*ConquestMapCenterOffsetX*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*ConquestMapCenterOffsetY*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 18 /*CameraAngle*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 20 /*CameraZoomMax*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 22 /*CameraZoomMin*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 24 /*CameraZoomDefault*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
