// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{


public enum DamageType : int
{
  Normal = 0,
  Critical = 1,
  IgnoreDefence = 2,
};


}
