// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EmblemExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EmblemExcel GetRootAsEmblemExcel(ByteBuffer _bb) { return GetRootAsEmblemExcel(_bb, new EmblemExcel()); }
  public static EmblemExcel GetRootAsEmblemExcel(ByteBuffer _bb, EmblemExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EmblemExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public FlatData.EmblemCategory Category { get { int o = __p.__offset(6); return o != 0 ? (FlatData.EmblemCategory)__p.bb.GetInt(o + __p.bb_pos) : FlatData.EmblemCategory.None; } }
  public FlatData.Rarity Rarity { get { int o = __p.__offset(8); return o != 0 ? (FlatData.Rarity)__p.bb.GetInt(o + __p.bb_pos) : FlatData.Rarity.N; } }
  public long DisplayOrder { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public uint LocalizeEtcId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public uint LocalizeCodeId { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public long UseAtLocalizeId { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public bool EmblemTextVisible { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public string IconPath { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconPathBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetIconPathBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetIconPathArray() { return __p.__vector_as_array<byte>(20); }
  public string EmblemIconPath { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmblemIconPathBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetEmblemIconPathBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetEmblemIconPathArray() { return __p.__vector_as_array<byte>(22); }
  public int EmblemIconNumControl { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string EmblemIconBGPath { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmblemIconBGPathBytes() { return __p.__vector_as_span<byte>(26, 1); }
#else
  public ArraySegment<byte>? GetEmblemIconBGPathBytes() { return __p.__vector_as_arraysegment(26); }
#endif
  public byte[] GetEmblemIconBGPathArray() { return __p.__vector_as_array<byte>(26); }
  public string EmblemBGPathJp { get { int o = __p.__offset(28); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmblemBGPathJpBytes() { return __p.__vector_as_span<byte>(28, 1); }
#else
  public ArraySegment<byte>? GetEmblemBGPathJpBytes() { return __p.__vector_as_arraysegment(28); }
#endif
  public byte[] GetEmblemBGPathJpArray() { return __p.__vector_as_array<byte>(28); }
  public string EmblemBGPathKr { get { int o = __p.__offset(30); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetEmblemBGPathKrBytes() { return __p.__vector_as_span<byte>(30, 1); }
#else
  public ArraySegment<byte>? GetEmblemBGPathKrBytes() { return __p.__vector_as_arraysegment(30); }
#endif
  public byte[] GetEmblemBGPathKrArray() { return __p.__vector_as_array<byte>(30); }
  public FlatData.EmblemDisplayType DisplayType { get { int o = __p.__offset(32); return o != 0 ? (FlatData.EmblemDisplayType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.EmblemDisplayType.Always; } }
  public string DisplayStartDate { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDisplayStartDateBytes() { return __p.__vector_as_span<byte>(34, 1); }
#else
  public ArraySegment<byte>? GetDisplayStartDateBytes() { return __p.__vector_as_arraysegment(34); }
#endif
  public byte[] GetDisplayStartDateArray() { return __p.__vector_as_array<byte>(34); }
  public string DisplayEndDate { get { int o = __p.__offset(36); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDisplayEndDateBytes() { return __p.__vector_as_span<byte>(36, 1); }
#else
  public ArraySegment<byte>? GetDisplayEndDateBytes() { return __p.__vector_as_arraysegment(36); }
#endif
  public byte[] GetDisplayEndDateArray() { return __p.__vector_as_array<byte>(36); }
  public int DislpayFavorLevel { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.EmblemCheckPassType CheckPassType { get { int o = __p.__offset(40); return o != 0 ? (FlatData.EmblemCheckPassType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.EmblemCheckPassType.None; } }
  public long EmblemParameter { get { int o = __p.__offset(42); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long CheckPassCount { get { int o = __p.__offset(44); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<FlatData.EmblemExcel> CreateEmblemExcel(FlatBufferBuilder builder,
      long Id = 0,
      FlatData.EmblemCategory Category = FlatData.EmblemCategory.None,
      FlatData.Rarity Rarity = FlatData.Rarity.N,
      long DisplayOrder = 0,
      uint LocalizeEtcId = 0,
      uint LocalizeCodeId = 0,
      long UseAtLocalizeId = 0,
      bool EmblemTextVisible = false,
      StringOffset IconPathOffset = default(StringOffset),
      StringOffset EmblemIconPathOffset = default(StringOffset),
      int EmblemIconNumControl = 0,
      StringOffset EmblemIconBGPathOffset = default(StringOffset),
      StringOffset EmblemBGPathJpOffset = default(StringOffset),
      StringOffset EmblemBGPathKrOffset = default(StringOffset),
      FlatData.EmblemDisplayType DisplayType = FlatData.EmblemDisplayType.Always,
      StringOffset DisplayStartDateOffset = default(StringOffset),
      StringOffset DisplayEndDateOffset = default(StringOffset),
      int DislpayFavorLevel = 0,
      FlatData.EmblemCheckPassType CheckPassType = FlatData.EmblemCheckPassType.None,
      long EmblemParameter = 0,
      long CheckPassCount = 0) {
    builder.StartTable(21);
    EmblemExcel.AddCheckPassCount(builder, CheckPassCount);
    EmblemExcel.AddEmblemParameter(builder, EmblemParameter);
    EmblemExcel.AddUseAtLocalizeId(builder, UseAtLocalizeId);
    EmblemExcel.AddDisplayOrder(builder, DisplayOrder);
    EmblemExcel.AddId(builder, Id);
    EmblemExcel.AddCheckPassType(builder, CheckPassType);
    EmblemExcel.AddDislpayFavorLevel(builder, DislpayFavorLevel);
    EmblemExcel.AddDisplayEndDate(builder, DisplayEndDateOffset);
    EmblemExcel.AddDisplayStartDate(builder, DisplayStartDateOffset);
    EmblemExcel.AddDisplayType(builder, DisplayType);
    EmblemExcel.AddEmblemBGPathKr(builder, EmblemBGPathKrOffset);
    EmblemExcel.AddEmblemBGPathJp(builder, EmblemBGPathJpOffset);
    EmblemExcel.AddEmblemIconBGPath(builder, EmblemIconBGPathOffset);
    EmblemExcel.AddEmblemIconNumControl(builder, EmblemIconNumControl);
    EmblemExcel.AddEmblemIconPath(builder, EmblemIconPathOffset);
    EmblemExcel.AddIconPath(builder, IconPathOffset);
    EmblemExcel.AddLocalizeCodeId(builder, LocalizeCodeId);
    EmblemExcel.AddLocalizeEtcId(builder, LocalizeEtcId);
    EmblemExcel.AddRarity(builder, Rarity);
    EmblemExcel.AddCategory(builder, Category);
    EmblemExcel.AddEmblemTextVisible(builder, EmblemTextVisible);
    return EmblemExcel.EndEmblemExcel(builder);
  }

  public static void StartEmblemExcel(FlatBufferBuilder builder) { builder.StartTable(21); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddCategory(FlatBufferBuilder builder, FlatData.EmblemCategory category) { builder.AddInt(1, (int)category, 0); }
  public static void AddRarity(FlatBufferBuilder builder, FlatData.Rarity rarity) { builder.AddInt(2, (int)rarity, 0); }
  public static void AddDisplayOrder(FlatBufferBuilder builder, long displayOrder) { builder.AddLong(3, displayOrder, 0); }
  public static void AddLocalizeEtcId(FlatBufferBuilder builder, uint localizeEtcId) { builder.AddUint(4, localizeEtcId, 0); }
  public static void AddLocalizeCodeId(FlatBufferBuilder builder, uint localizeCodeId) { builder.AddUint(5, localizeCodeId, 0); }
  public static void AddUseAtLocalizeId(FlatBufferBuilder builder, long useAtLocalizeId) { builder.AddLong(6, useAtLocalizeId, 0); }
  public static void AddEmblemTextVisible(FlatBufferBuilder builder, bool emblemTextVisible) { builder.AddBool(7, emblemTextVisible, false); }
  public static void AddIconPath(FlatBufferBuilder builder, StringOffset iconPathOffset) { builder.AddOffset(8, iconPathOffset.Value, 0); }
  public static void AddEmblemIconPath(FlatBufferBuilder builder, StringOffset emblemIconPathOffset) { builder.AddOffset(9, emblemIconPathOffset.Value, 0); }
  public static void AddEmblemIconNumControl(FlatBufferBuilder builder, int emblemIconNumControl) { builder.AddInt(10, emblemIconNumControl, 0); }
  public static void AddEmblemIconBGPath(FlatBufferBuilder builder, StringOffset emblemIconBGPathOffset) { builder.AddOffset(11, emblemIconBGPathOffset.Value, 0); }
  public static void AddEmblemBGPathJp(FlatBufferBuilder builder, StringOffset emblemBGPathJpOffset) { builder.AddOffset(12, emblemBGPathJpOffset.Value, 0); }
  public static void AddEmblemBGPathKr(FlatBufferBuilder builder, StringOffset emblemBGPathKrOffset) { builder.AddOffset(13, emblemBGPathKrOffset.Value, 0); }
  public static void AddDisplayType(FlatBufferBuilder builder, FlatData.EmblemDisplayType displayType) { builder.AddInt(14, (int)displayType, 0); }
  public static void AddDisplayStartDate(FlatBufferBuilder builder, StringOffset displayStartDateOffset) { builder.AddOffset(15, displayStartDateOffset.Value, 0); }
  public static void AddDisplayEndDate(FlatBufferBuilder builder, StringOffset displayEndDateOffset) { builder.AddOffset(16, displayEndDateOffset.Value, 0); }
  public static void AddDislpayFavorLevel(FlatBufferBuilder builder, int dislpayFavorLevel) { builder.AddInt(17, dislpayFavorLevel, 0); }
  public static void AddCheckPassType(FlatBufferBuilder builder, FlatData.EmblemCheckPassType checkPassType) { builder.AddInt(18, (int)checkPassType, 0); }
  public static void AddEmblemParameter(FlatBufferBuilder builder, long emblemParameter) { builder.AddLong(19, emblemParameter, 0); }
  public static void AddCheckPassCount(FlatBufferBuilder builder, long checkPassCount) { builder.AddLong(20, checkPassCount, 0); }
  public static Offset<FlatData.EmblemExcel> EndEmblemExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.EmblemExcel>(o);
  }
  public EmblemExcelT UnPack() {
    var _o = new EmblemExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EmblemExcelT _o) {
    _o.Id = this.Id;
    _o.Category = this.Category;
    _o.Rarity = this.Rarity;
    _o.DisplayOrder = this.DisplayOrder;
    _o.LocalizeEtcId = this.LocalizeEtcId;
    _o.LocalizeCodeId = this.LocalizeCodeId;
    _o.UseAtLocalizeId = this.UseAtLocalizeId;
    _o.EmblemTextVisible = this.EmblemTextVisible;
    _o.IconPath = this.IconPath;
    _o.EmblemIconPath = this.EmblemIconPath;
    _o.EmblemIconNumControl = this.EmblemIconNumControl;
    _o.EmblemIconBGPath = this.EmblemIconBGPath;
    _o.EmblemBGPathJp = this.EmblemBGPathJp;
    _o.EmblemBGPathKr = this.EmblemBGPathKr;
    _o.DisplayType = this.DisplayType;
    _o.DisplayStartDate = this.DisplayStartDate;
    _o.DisplayEndDate = this.DisplayEndDate;
    _o.DislpayFavorLevel = this.DislpayFavorLevel;
    _o.CheckPassType = this.CheckPassType;
    _o.EmblemParameter = this.EmblemParameter;
    _o.CheckPassCount = this.CheckPassCount;
  }
  public static Offset<FlatData.EmblemExcel> Pack(FlatBufferBuilder builder, EmblemExcelT _o) {
    if (_o == null) return default(Offset<FlatData.EmblemExcel>);
    var _IconPath = _o.IconPath == null ? default(StringOffset) : builder.CreateString(_o.IconPath);
    var _EmblemIconPath = _o.EmblemIconPath == null ? default(StringOffset) : builder.CreateString(_o.EmblemIconPath);
    var _EmblemIconBGPath = _o.EmblemIconBGPath == null ? default(StringOffset) : builder.CreateString(_o.EmblemIconBGPath);
    var _EmblemBGPathJp = _o.EmblemBGPathJp == null ? default(StringOffset) : builder.CreateString(_o.EmblemBGPathJp);
    var _EmblemBGPathKr = _o.EmblemBGPathKr == null ? default(StringOffset) : builder.CreateString(_o.EmblemBGPathKr);
    var _DisplayStartDate = _o.DisplayStartDate == null ? default(StringOffset) : builder.CreateString(_o.DisplayStartDate);
    var _DisplayEndDate = _o.DisplayEndDate == null ? default(StringOffset) : builder.CreateString(_o.DisplayEndDate);
    return CreateEmblemExcel(
      builder,
      _o.Id,
      _o.Category,
      _o.Rarity,
      _o.DisplayOrder,
      _o.LocalizeEtcId,
      _o.LocalizeCodeId,
      _o.UseAtLocalizeId,
      _o.EmblemTextVisible,
      _IconPath,
      _EmblemIconPath,
      _o.EmblemIconNumControl,
      _EmblemIconBGPath,
      _EmblemBGPathJp,
      _EmblemBGPathKr,
      _o.DisplayType,
      _DisplayStartDate,
      _DisplayEndDate,
      _o.DislpayFavorLevel,
      _o.CheckPassType,
      _o.EmblemParameter,
      _o.CheckPassCount);
  }
}

public class EmblemExcelT
{
  [Newtonsoft.Json.JsonProperty("Id")]
  public long Id { get; set; }
  [Newtonsoft.Json.JsonProperty("Category")]
  public FlatData.EmblemCategory Category { get; set; }
  [Newtonsoft.Json.JsonProperty("Rarity")]
  public FlatData.Rarity Rarity { get; set; }
  [Newtonsoft.Json.JsonProperty("DisplayOrder")]
  public long DisplayOrder { get; set; }
  [Newtonsoft.Json.JsonProperty("LocalizeEtcId")]
  public uint LocalizeEtcId { get; set; }
  [Newtonsoft.Json.JsonProperty("LocalizeCodeId")]
  public uint LocalizeCodeId { get; set; }
  [Newtonsoft.Json.JsonProperty("UseAtLocalizeId")]
  public long UseAtLocalizeId { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemTextVisible")]
  public bool EmblemTextVisible { get; set; }
  [Newtonsoft.Json.JsonProperty("IconPath")]
  public string IconPath { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemIconPath")]
  public string EmblemIconPath { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemIconNumControl")]
  public int EmblemIconNumControl { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemIconBGPath")]
  public string EmblemIconBGPath { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemBGPathJp")]
  public string EmblemBGPathJp { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemBGPathKr")]
  public string EmblemBGPathKr { get; set; }
  [Newtonsoft.Json.JsonProperty("DisplayType")]
  public FlatData.EmblemDisplayType DisplayType { get; set; }
  [Newtonsoft.Json.JsonProperty("DisplayStartDate")]
  public string DisplayStartDate { get; set; }
  [Newtonsoft.Json.JsonProperty("DisplayEndDate")]
  public string DisplayEndDate { get; set; }
  [Newtonsoft.Json.JsonProperty("DislpayFavorLevel")]
  public int DislpayFavorLevel { get; set; }
  [Newtonsoft.Json.JsonProperty("CheckPassType")]
  public FlatData.EmblemCheckPassType CheckPassType { get; set; }
  [Newtonsoft.Json.JsonProperty("EmblemParameter")]
  public long EmblemParameter { get; set; }
  [Newtonsoft.Json.JsonProperty("CheckPassCount")]
  public long CheckPassCount { get; set; }

  public EmblemExcelT() {
    this.Id = 0;
    this.Category = FlatData.EmblemCategory.None;
    this.Rarity = FlatData.Rarity.N;
    this.DisplayOrder = 0;
    this.LocalizeEtcId = 0;
    this.LocalizeCodeId = 0;
    this.UseAtLocalizeId = 0;
    this.EmblemTextVisible = false;
    this.IconPath = null;
    this.EmblemIconPath = null;
    this.EmblemIconNumControl = 0;
    this.EmblemIconBGPath = null;
    this.EmblemBGPathJp = null;
    this.EmblemBGPathKr = null;
    this.DisplayType = FlatData.EmblemDisplayType.Always;
    this.DisplayStartDate = null;
    this.DisplayEndDate = null;
    this.DislpayFavorLevel = 0;
    this.CheckPassType = FlatData.EmblemCheckPassType.None;
    this.EmblemParameter = 0;
    this.CheckPassCount = 0;
  }
}


static public class EmblemExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Category*/, 4 /*FlatData.EmblemCategory*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Rarity*/, 4 /*FlatData.Rarity*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*DisplayOrder*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*LocalizeEtcId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*LocalizeCodeId*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*UseAtLocalizeId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 18 /*EmblemTextVisible*/, 1 /*bool*/, 1, false)
      && verifier.VerifyString(tablePos, 20 /*IconPath*/, false)
      && verifier.VerifyString(tablePos, 22 /*EmblemIconPath*/, false)
      && verifier.VerifyField(tablePos, 24 /*EmblemIconNumControl*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 26 /*EmblemIconBGPath*/, false)
      && verifier.VerifyString(tablePos, 28 /*EmblemBGPathJp*/, false)
      && verifier.VerifyString(tablePos, 30 /*EmblemBGPathKr*/, false)
      && verifier.VerifyField(tablePos, 32 /*DisplayType*/, 4 /*FlatData.EmblemDisplayType*/, 4, false)
      && verifier.VerifyString(tablePos, 34 /*DisplayStartDate*/, false)
      && verifier.VerifyString(tablePos, 36 /*DisplayEndDate*/, false)
      && verifier.VerifyField(tablePos, 38 /*DislpayFavorLevel*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 40 /*CheckPassType*/, 4 /*FlatData.EmblemCheckPassType*/, 4, false)
      && verifier.VerifyField(tablePos, 42 /*EmblemParameter*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 44 /*CheckPassCount*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
