// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldRewardExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static FieldRewardExcel GetRootAsFieldRewardExcel(ByteBuffer _bb) { return GetRootAsFieldRewardExcel(_bb, new FieldRewardExcel()); }
  public static FieldRewardExcel GetRootAsFieldRewardExcel(ByteBuffer _bb, FieldRewardExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldRewardExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long GroupId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int RewardProb { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public FlatData.ParcelType RewardParcelType { get { int o = __p.__offset(8); return o != 0 ? (FlatData.ParcelType)__p.bb.GetInt(o + __p.bb_pos) : FlatData.ParcelType.None; } }
  public long RewardId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public int RewardAmount { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatData.FieldRewardExcel> CreateFieldRewardExcel(FlatBufferBuilder builder,
      long GroupId = 0,
      int RewardProb = 0,
      FlatData.ParcelType RewardParcelType = FlatData.ParcelType.None,
      long RewardId = 0,
      int RewardAmount = 0) {
    builder.StartTable(5);
    FieldRewardExcel.AddRewardId(builder, RewardId);
    FieldRewardExcel.AddGroupId(builder, GroupId);
    FieldRewardExcel.AddRewardAmount(builder, RewardAmount);
    FieldRewardExcel.AddRewardParcelType(builder, RewardParcelType);
    FieldRewardExcel.AddRewardProb(builder, RewardProb);
    return FieldRewardExcel.EndFieldRewardExcel(builder);
  }

  public static void StartFieldRewardExcel(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddGroupId(FlatBufferBuilder builder, long groupId) { builder.AddLong(0, groupId, 0); }
  public static void AddRewardProb(FlatBufferBuilder builder, int rewardProb) { builder.AddInt(1, rewardProb, 0); }
  public static void AddRewardParcelType(FlatBufferBuilder builder, FlatData.ParcelType rewardParcelType) { builder.AddInt(2, (int)rewardParcelType, 0); }
  public static void AddRewardId(FlatBufferBuilder builder, long rewardId) { builder.AddLong(3, rewardId, 0); }
  public static void AddRewardAmount(FlatBufferBuilder builder, int rewardAmount) { builder.AddInt(4, rewardAmount, 0); }
  public static Offset<FlatData.FieldRewardExcel> EndFieldRewardExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatData.FieldRewardExcel>(o);
  }
  public FieldRewardExcelT UnPack() {
    var _o = new FieldRewardExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldRewardExcelT _o) {
    _o.GroupId = this.GroupId;
    _o.RewardProb = this.RewardProb;
    _o.RewardParcelType = this.RewardParcelType;
    _o.RewardId = this.RewardId;
    _o.RewardAmount = this.RewardAmount;
  }
  public static Offset<FlatData.FieldRewardExcel> Pack(FlatBufferBuilder builder, FieldRewardExcelT _o) {
    if (_o == null) return default(Offset<FlatData.FieldRewardExcel>);
    return CreateFieldRewardExcel(
      builder,
      _o.GroupId,
      _o.RewardProb,
      _o.RewardParcelType,
      _o.RewardId,
      _o.RewardAmount);
  }
}

public class FieldRewardExcelT
{
  [Newtonsoft.Json.JsonProperty("GroupId")]
  public long GroupId { get; set; }
  [Newtonsoft.Json.JsonProperty("RewardProb")]
  public int RewardProb { get; set; }
  [Newtonsoft.Json.JsonProperty("RewardParcelType")]
  public FlatData.ParcelType RewardParcelType { get; set; }
  [Newtonsoft.Json.JsonProperty("RewardId")]
  public long RewardId { get; set; }
  [Newtonsoft.Json.JsonProperty("RewardAmount")]
  public int RewardAmount { get; set; }

  public FieldRewardExcelT() {
    this.GroupId = 0;
    this.RewardProb = 0;
    this.RewardParcelType = FlatData.ParcelType.None;
    this.RewardId = 0;
    this.RewardAmount = 0;
  }
}


static public class FieldRewardExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*GroupId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*RewardProb*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*RewardParcelType*/, 4 /*FlatData.ParcelType*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*RewardId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*RewardAmount*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
