// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatData
{


public enum NoticeType : int
{
  None = 0,
  Notice = 1,
  Event = 2,
};


}
